- Makefile
- cmd/headscale/headscale.go
- cmd/headscale/headscale_test.go
Add some config loading and validation tests.
> Add first tests

- .github/workflows/ci.yml
- cmd/headscale/headscale.go
- cmd/headscale/headscale_test.go
This commit adds a basic CI workflow with github actions, configured to run on push and PR. It will run `make test`, `make lint`, and `make`.
> Add a basic CI workflow with github actions

- api.go
- cli.go
- machine.go
- preauth_keys.go
- preauth_keys_test.go
- utils.go
This is a WIP PR, to add a bit of visibility to this feature.
> Support for pre auth keys

- .github/workflows/ci.yml
- api.go
- go.sum
- machine_test.go
- namespaces_test.go
- routes_test.go
Nothing special, just adding some more test coverage.
> Add more tests

- app.go
- cli_test.go
- cmd/headscale/cli/nodes.go
- preauth_keys_test.go
Remove superfluous test support code. Fix bug in node list cli command. Add tests.
> a bunch of smaller fixes

- Dockerfile
- k8s/.gitignore
- k8s/README.md
- k8s/base/configmap.yaml
- k8s/base/ingress.yaml
- k8s/base/kustomization.yaml
- k8s/base/service.yaml
- k8s/headscale.bash
- k8s/init.bash
- k8s/install-cert-manager.bash
- k8s/postgres/deployment.yaml
- k8s/postgres/kustomization.yaml
- k8s/postgres/postgres-service.yaml
- k8s/postgres/postgres-statefulset.yaml
- k8s/production-tls/ingress-patch.yaml
- k8s/production-tls/kustomization.yaml
- k8s/production-tls/production-issuer.yaml
- k8s/sqlite/kustomization.yaml
- k8s/sqlite/statefulset.yaml
- k8s/staging-tls/ingress-patch.yaml
- k8s/staging-tls/kustomization.yaml
- k8s/staging-tls/staging-issuer.yaml
Tested with Rancher k3s and a couple of NixOS containers running tailscale clients against it.
> Add k8s deployment, standalone app Dockerfile.

- api.go
As reported in Gitter, it might be that ephemeral tailscale clients get stuck when headscale is stop and restarted. 
Sending back HTTP errors will make the tailsclient to restart the auth flow
> Added HTTP responses on map errors

- cmd/headscale/cli/utils.go
- cmd/headscale/headscale_test.go
443 into a warning, not an error, refs #53.
> Turn the combination of TLS-ALPN-01 and listen_addr on a port other than

- cmd/headscale/cli/nodes.go
- cmd/headscale/headscale.go
- go.mod
- go.sum
- machine.go
- machine_test.go
This PR adds the subcommand to (soft) delete nodes from the headscale DB.
> Implement node deletion

- routes.go
Enabling routes was not sending immediate notifications to the nodes in the tailnet / namespaces. This fixes it...
> Send notifications when enabling a route

- Dockerfile
> Dockerfile: add golang tag

- .github/workflows/release.yml
Add full version to docker tag like 0.8.1
> workflows/release: add docker full version tag

- README.md
- integration_test.go
- machine.go
A very low-hanging fruit here. This PR just adds support for Taildrop (tailscale filesharing, https://tailscale.com/kb/1106/taildrop/)
> Add support for Taildrop (file sharing)

- cmd/headscale/cli/namespaces.go
- namespaces.go
- namespaces_test.go
- preauth_keys.go
Add a confirmation prompt and make sure to also delete any associated preauthkeys. This fixes issue #217.
> Improvements for namespace deletion

- app.go
changes "postgresql" to "postgres"
> Revert postgres constant value

- CHANGELOG.md
- README.md
> Prepare CHANGELOG for 0.12.1

- .github/workflows/release.yml
> Fix docker release

- docs/Running.md
I will have a look at improving this on my flight back home in a weeks time.
> Add note about outdated docs until we fix them

- docs/running-headscale-container.md
- Fix URLs referring to files in this repository
- Better explain that we are creating the headscale directory and running the commands on the host Docker node
- Place instructions to download example config file to use as config file, as recommended steps.
> Improve Docker docs

- docs/running-headscale-linux.md
> Fix example config link

- CHANGELOG.md
> Prepare CHANGELOG for 0.12.2 

- .github/workflows/release.yml
- Dockerfile.alpine
> Add docker alpine image

- README.md
- docs/running-headscale-linux.md
- [] raised a GitHub issue or discussed it on the projects chat beforehand
> Fix doc typos

- CHANGELOG.md
> Tag 0.12.4 in CHANGELOG

- .goreleaser.yml
`go mod tidy` is not happy about only 1.17 `go.mod` so tell it to only care about that.
> Set goreleaser to only care about Go 1.17

- .github/CODEOWNERS
> CODEOWNER: add renovate config ohdearaugustin

- docs/README.md
> Fix spelling error

- .github/workflows/contributors.yml
> contributor: set specific version

- README.md
Added FreeBSD to the supported clients
Now in FreeBSD ports: https://www.freshports.org/security/headscale/
- [] raised a GitHub issue or discussed it on the projects chat beforehand
> Added FreeBSD to the supported clients

- CHANGELOG.md
- acls.go
- acls_test.go
> feat(acls): normalize the group name

- app.go
By allowing API keys to be validated
> Fix API access

- CHANGELOG.md
- oidc.go
The previous code resetted the expiry time to be expired.  So the machine was never reauthenticated
closes #508
> fix(oidc): Reset expiry for reauthentication

- oidc.go
> feat(oidc): add debug log

- CHANGELOG.md
> Prepare CHANGELOG for v0.15.0

- docs/running-headscale-container.md
While configuring a Docker setup I noticed that the docs could use some enhancements.
> Docker docs enhancements

- .github/ISSUE_TEMPLATE/config.yml
- README.md
Fixes: https://github.com/juanfont/headscale/issues/533
> fix discord invite

- docs/running-headscale-linux.md
[Suggested-by: Rendezvous](https://discord.com/channels/896711691637780480/896711692120129540/965005644149162084)
I also took the liberty of combining some commands.
> Clarified systemd friendly path

- cmd/headscale/cli/nodes.go
> show ipv4 address first in node list

- docs/remote-cli.md
> fixed typo

- CHANGELOG.md
- cmd/headscale/cli/routes.go
- integration_cli_test.go
----------------------
Added cli functionality to enable all routes on host.
> Add --all (-a) flag to enable routes command (implements #360)

- .goreleaser.yml
- CHANGELOG.md
> Drop arm32 (armhf) for linux and add Darwin arm64

- Makefile
> some GOOS do not support pie build, detect in makefile and fall back to non-pie build

- Dockerfile
- Dockerfile.alpine
- Dockerfile.debug
> fix typo for GGO->CGO

- CHANGELOG.md
- cmd/headscale/cli/dump_config.go
- cmd/headscale/cli/root.go
- cmd/headscale/cli/utils.go
- cmd/headscale/headscale.go
- cmd/headscale/headscale_test.go
- integration_cli_test.go
- integration_test/etc/alt-config.dump.gold.yaml
- integration_test/etc/alt-config.yaml
- integration_test/etc/config.dump.gold.yaml
> Override config file via cli

- docs/README.md
- docs/running-headscale-openbsd.md
> OpenBSD doc

- Makefile
> fix issue 635

- .github/workflows/release.yml
- Dockerfile
- Dockerfile.alpine
- Dockerfile.debug
> Add version info to binary in Docker container

- CHANGELOG.md
- cmd/headscale/cli/nodes.go
> more intuitive output of node ls

- .github/workflows/test-integration.yml
- Makefile
- integration_cli_test.go
- integration_common_test.go
- integration_embedded_derp_test.go
- integration_general_test.go
- integration_test.go
This is a PR to troubleshoot and improve the execution of integration tests.
> Improvements in integration tests

- .github/workflows/lint.yml
Just a minor update to try to fix the proto-lint flow
> Update buf setup action for proto-lint

- docs/acls.md
> typo fixed from advertised to advertise

- oidc.go
`gocyclo` complains about `OIDCCallback` method complexity. This PR decomposes this method into smaller ones to simplify it.
> Decompose OIDCCallback method

- api.go
Another fix for another occurrence of MachineKey being used as ID.
My bad, again. We really need some integration tests on the auth process. I will look at it after Noise.
> Fixed another recurrence of MachineKey

- CHANGELOG.md
> Added changelog entries for 0.16.x

- swagger.go
> Fix charset typo in swagger.go

- CHANGELOG.md
- cmd/headscale/cli/root.go
- integration_cli_test.go
- integration_test/etc/alt-env-config.dump.gold.yaml
- integration_test/etc/alt-env-config.yaml
> Env config

- proto/buf.lock
Fixes #794. Let me know if I need to add an entry to the CHANGELOG!
> Run `buf mod update` in protos/

- app.go
Fix https://github.com/juanfont/headscale/issues/836
> Fix warning on OIDC initialisation success

- .github/workflows/test-integration-cli.yml
- .github/workflows/test-integration-derp.yml
- .github/workflows/test-integration-general.yml
- .github/workflows/test-integration-oidc.yml
Let them run in parallel, on separate vms
> Split integration tests into seperate jobs

- cmd/headscale/cli/root.go
> Fix no arguments panic

- Makefile
- flake.nix
- integration_cli_test.go
- integration_common_test.go
- integration_embedded_derp_test.go
- integration_general_test.go
- integration_oidc_test.go
> Do not use build tags for running integration tests

- integration/general_test.go
- integration/scenario.go
- integration/scenario_test.go
- integration/tailscale.go
- integration/tsic/tsic.go
> Integration: make TailscaleClient interface

- docs/running-headscale-container.md
> Unify code snippet comment location

- integration/general_test.go
- integration/tailscale.go
- integration/tsic/tsic.go
> Migrate taildrop test to v2

- app.go
- flake.nix
- go.mod
- go.sum
- namespaces.go
- protocol_common_poll.go
Updates `xsync` to v2 and simplifies the code slightly.
> Simplify code around latest state change map updates

- integration/cli_test.go
- integration/control.go
- integration/hsic/hsic.go
> Integration v2: initial CLI command work

- cmd/headscale/cli/utils.go
Should fix #523.
Should fix #885.
> Give user better feedback if headscale socket is unwritable

- Dockerfile.debug
- integration/hsic/config.go
- integration/hsic/hsic.go
- integration/scenario.go
> integration: add headscale configuration programatically

- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test-integration-cli.yml
- .github/workflows/test-integration-derp.yml
- .github/workflows/test-integration-oidc.yml
- .github/workflows/test-integration-v2-general.yml
- .github/workflows/test.yml
We have a lot of them named CI in Actions, makes it hard to navigate...
> Give workflows better names

- .golangci.yaml
- cmd/headscale/cli/debug.go
- grpcv1.go
- integration_cli_test.go
- integration_oidc_test.go
- machine.go
- oidc.go
- protocol_common.go
> fix bug in #912

- protocol_common_poll.go
Remove hardcoded statement in mapPoll update
> Fix noise mapResponse updates, Fixes #838

- .golangci.yaml
- oidc.go
> Fixed minor linting issues

- .github/workflows/release.yml
Tags every new release, regardless of if it is a pre-release, with the `develop` tag. This means users will have four choices if they want to follow along without having to bump the container tag on every release:
- `latest`: Latest stable release.
- `latest-debug`: Latest stable release, in the debugging container.
- `develop`: Latest release, regardless of if it is a beta or stable.
- `develop-debug`: Latest release, regardless of if it is a beta or stable, in the debugging container.
> Release: tag every release with develop

- cmd/headscale/cli/root.go
Small PR to remove the requirement for a valid config when generating the CLI completion.
> Fix shell completion issues

- integration/hsic/hsic.go
- integration/integrationutil/util.go
> Remove some very verbose error outputs

- Makefile
- integration/auth_oidc_test.go
- integration/auth_web_flow_test.go
- integration/general_test.go
- integration/scenario_test.go
> Mark all new integration tests to run in parallel

- api_common.go
- namespaces.go
- namespaces_test.go
> Make displayName include basedomain if set

- CHANGELOG.md
Signed-off-by: Kristoffer Dalby <kradalby@kradalby.no>
> Mark some changes as more important

- integration/general_test.go
- integration/scenario_test.go
Arguably, this subtests are not really subtests.
> Ignore tparallel where it doesnt make sense

- CHANGELOG.md
We missed this one, called out several places. 
> Add breaking change about noise private path

- CHANGELOG.md
Very minor PR to have where to write changes :)
> Added changelog for 0.17.1

- .github/workflows/test-integration-v2-kradalby.yml
> Murder docker container and network before run

- CHANGELOG.md
- config.go
- integration_test/etc/alt-config.dump.gold.yaml
- integration_test/etc/alt-config.yaml
- integration_test/etc/alt-env-config.dump.gold.yaml
- integration_test/etc/alt-env-config.yaml
- integration_test/etc/config.dump.gold.yaml
> Set db_ssl to false by default, fixes #1043

- .github/workflows/test-integration-v2-kradalby.yml
> dont fail docker if nothing to delete

- flake.nix
- gen/go/headscale/v1/headscale.pb.gw.go
> upgrade grpc-gateway plugin

- machine.go
- routes.go
Just a small PR to set us back to green.
> Minor linting fixes

- .github/FUNDING.yml
After some internal discussions, lets add a ko-fi.com sponsor button :)
> Add ko-fi sponsor button

- platform_config.go
- templates/apple.html
> update macos check template

- templates/apple.html
> templates: fix typo "custm" -> "custom"

- docs/reverse-proxy.md
As suggested by @juanfont in the headscale Discord.
> Add Caddy instructions to reverse_proxy.md

- machine.go
- routes_test.go
Just a small PR  to send in AllowedIPs both primary routes AND enabled exit routes
> Fix exit nodes funcionality

- .github/workflows/test-integration-v2-TestAuthKeyLogoutAndRelogin.yaml
- .github/workflows/test-integration-v2-TestAuthWebFlowAuthenticationPingAll.yaml
- .github/workflows/test-integration-v2-TestAuthWebFlowLogoutAndRelogin.yaml
- .github/workflows/test-integration-v2-TestCreateTailscale.yaml
- .github/workflows/test-integration-v2-TestEnablingRoutes.yaml
- .github/workflows/test-integration-v2-TestHeadscale.yaml
- .github/workflows/test-integration-v2-TestNamespaceCommand.yaml
- .github/workflows/test-integration-v2-TestOIDCAuthenticationPingAll.yaml
- .github/workflows/test-integration-v2-TestOIDCExpireNodes.yaml
- .github/workflows/test-integration-v2-TestPingAllByHostname.yaml
- .github/workflows/test-integration-v2-TestPingAllByIP.yaml
- .github/workflows/test-integration-v2-TestPreAuthKeyCommand.yaml
- .github/workflows/test-integration-v2-TestPreAuthKeyCommandReusableEphemeral.yaml
- .github/workflows/test-integration-v2-TestPreAuthKeyCommandWithoutExpiry.yaml
- .github/workflows/test-integration-v2-TestResolveMagicDNS.yaml
- .github/workflows/test-integration-v2-TestSSHIsBlockedInACL.yaml
- .github/workflows/test-integration-v2-TestSSHMultipleNamespacesAllToAll.yaml
- .github/workflows/test-integration-v2-TestSSHNoSSHConfigured.yaml
- .github/workflows/test-integration-v2-TestSSHOneNamespaceAllToAll.yaml
- .github/workflows/test-integration-v2-TestSSNamespaceOnlyIsolation.yaml
- .github/workflows/test-integration-v2-TestTaildrop.yaml
- .github/workflows/test-integration-v2-TestTailscaleNodesJoiningHeadcale.yaml
- cmd/gh-action-integration-generator/main.go
> Limit run regex for generated workflows

- CHANGELOG.md
> Added entry for performance improvements in ACLs

- config-example.yaml
we cant actually have arbitrary ip ranges, add a note about that.
updates #1050
> update ip_prefixes docs

- api.go
related to https://github.com/juanfont/headscale/pull/1144
Signed-off-by: Christian Heusel <christian@heusel.eu>
> Update the node join instruction to reference "username"

- integration/auth_web_flow_test.go
This builds on https://github.com/juanfont/headscale/pull/1150 as I noticed that there also is a test that checks whether the join works.
Signed-off-by: Christian Heusel <christian@heusel.eu>
> modify the test to reflect the changes on the webinterface

- CHANGELOG.md
- cmd/headscale/cli/debug.go
- cmd/headscale/cli/nodes.go
- cmd/headscale/cli/preauthkeys.go
- cmd/headscale/cli/root.go
- cmd/headscale/cli/users.go
> Mark -n and --namespace as deprecated

- CHANGELOG.md
Preparation PR to have room for v0.20.0 in the changelog
> Updated changelog for v0.20.0

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
> Cancel old builds if new commits appear

- acls.go
- acls_test.go
> Rename IP specific function, add missing Host field test case

- .github/workflows/test-integration-v2-TestAuthKeyLogoutAndRelogin.yaml
- .github/workflows/test-integration-v2-TestAuthWebFlowAuthenticationPingAll.yaml
- .github/workflows/test-integration-v2-TestAuthWebFlowLogoutAndRelogin.yaml
- .github/workflows/test-integration-v2-TestCreateTailscale.yaml
- .github/workflows/test-integration-v2-TestEnablingRoutes.yaml
- .github/workflows/test-integration-v2-TestEphemeral.yaml
- .github/workflows/test-integration-v2-TestHeadscale.yaml
- .github/workflows/test-integration-v2-TestOIDCAuthenticationPingAll.yaml
- .github/workflows/test-integration-v2-TestOIDCExpireNodesBasedOnTokenExpiry.yaml
- .github/workflows/test-integration-v2-TestPingAllByHostname.yaml
- .github/workflows/test-integration-v2-TestPingAllByIP.yaml
- .github/workflows/test-integration-v2-TestPreAuthKeyCommand.yaml
- .github/workflows/test-integration-v2-TestPreAuthKeyCommandReusableEphemeral.yaml
- .github/workflows/test-integration-v2-TestPreAuthKeyCommandWithoutExpiry.yaml
- .github/workflows/test-integration-v2-TestResolveMagicDNS.yaml
- .github/workflows/test-integration-v2-TestSSHIsBlockedInACL.yaml
- .github/workflows/test-integration-v2-TestSSHMultipleUsersAllToAll.yaml
- .github/workflows/test-integration-v2-TestSSHOneUserAllToAll.yaml
- .github/workflows/test-integration-v2-TestSSUserOnlyIsolation.yaml
- .github/workflows/test-integration-v2-TestTaildrop.yaml
- .github/workflows/test-integration-v2-TestTailscaleNodesJoiningHeadcale.yaml
- .github/workflows/test-integration-v2-TestUserCommand.yaml
- cmd/gh-action-integration-generator/main.go
- integration/README.md
> Use ripgrep to find list of integration tests

- cmd/gh-action-integration-generator/main.go
> Remove all tests before generating new ones

- README.md
> Add list of talks to the readme

- .github/workflows/lint.yml
Update the prettier action to 4.2 https://github.com/creyD/prettier_action, as it is currently failing.
> Update prettier action

- docs/oidc.md
I've been meaning to add this, as I was a little confused what the steps were for Google OAuth, and there are many differing solutions around. This is the easiest way to do things (and very obvious once you understand).
I also have screenshots of the process, but honestly it's pretty straight forward. The screenshots are just arrows to what to click on.
> Add steps for Google OAuth for OIDC

- .github/workflows/lint.yml
- cmd/headscale/cli/configtest.go
- integration/hsic/hsic.go
Just a very very very minor PR.
> Fix various linting issues + golang-lint upgrade

- README.md
Added my project to this section per #234
Reference discussion in #234 
New to all this.  Please let me know if this is the wrong place!
> Add Graphical Control Panels section to README

- .github/workflows/test-integration-v2-TestACLHostsInNetMapTable.yaml
- acls.go
- app.go
- integration/acl_test.go
- machine.go
- machine_test.go
- utils.go
This PR picks up @QZAiXH changes from #1239, but rewrites them slightly to make it conform more to the current code and adds documentation. 
In addition it lifts one of the ACL integration tests from my experimental #1069 PR.
> MapResponse optimalisations, peer list integration tests

- .github/workflows/test-integration-v2-TestACLAllowUser80Dst.yaml
- integration/acl_test.go
- integration/tailscale.go
- integration/tsic/tsic.go
> Add ACL test for limiting a single port.

- cmd/headscale/cli/utils.go
- derp.go
- go.mod
> Do not use yaml.v2 and yaml.v3 as direct dependency

- docs/acls.md
> updated to ACL doc

- acls.go
- acls_test.go
- integration/acl_test.go
- machine.go
> Add tests to verify "Hosts" aliases in ACL

- docs/windows-client.md
- templates/windows.html
I've added some Powershell commands to edit the registry as an option beyond using regedit.
> Adding Powershell commands to Windows instructions

- .golangci.yaml
Small PR to fix some broken & deprecated linters.
> Remove deprecated/broken linters

- .goreleaser.yml
Fixes issue with goreleaser and multiarch releases.
> Fix binary releases

- .gitignore
- flake.lock
- flake.nix
> Update flakes, add some quality of life improvements

- CHANGELOG.md
- docs/packaging/headscale.systemd.service
> Add more capabilities for systemd

- .github/workflows/test-integration-v2-TestDERPServerScenario.yaml
- integration/control.go
- integration/embedded_derp_test.go
- integration/hsic/hsic.go
- integration/tailscale.go
- integration/tsic/tsic.go
- integration/utils.go
This PR ports the DERP integration tests to the new scenario model, in preparation to expand the capabilities of the DERP server (i.e., verify clients).
> Port embedded DERP integration tests to new model

- .goreleaser.yml
- CHANGELOG.md
> Move systemd service file to standard location

- README.md
Updating the doc path to be the doc website url as it's a better documentation tool, I didn't update the CHANGELOG as it doesn't concern the app itself. Let me know if I should do this
> Fix : Updating the doc path

- mkdocs.yml
This fix should change the edit branch to main in the documentation
I didn't update the CHANGELOG, as it doesn't concern the app itself. Let me know if I should do this
> Fix : Change master branch to main

- config-example.yaml
Fix #1413 
- [ x] read the [CONTRIBUTING guidelines](README.md#contributing)
- [ x] raised a GitHub issue or discussed it on the projects chat beforehand
> Revert unix_socket to default value

- config.go
The only supported prefixes to assign client IPs by the Tailscale client are 100.64.0.0/10 and fd7a:115c:a1e0::/48.
Despite that, we allow users to setup arbitrary ranges in the Headscale config. This kinda work, but also don't:
https://github.com/juanfont/headscale/issues/1409
https://github.com/juanfont/headscale/issues/1050
https://github.com/juanfont/headscale/issues/148
(and more)
This PR adds a warning in the config when users have other IP prefixes.
> Give a warning when users have set an unsupported prefix

- docs/index.md
- mkdocs.yml
Improved some stuff in the website.
> Improved website

- CHANGELOG.md
- README.md
- docs/web-ui.md
- mkdocs.yml
> Added web ui section

- hscontrol/types/machine.go
- hscontrol/types/machine_test.go
Fixes #1344
Apologies for the previous pull request containing errors. I have now made the necessary revisions.
> Fix IP Address Order Bug

- docs/packaging/headscale.systemd.service
> redundant line removed from systemd.service

- CHANGELOG.md
- hscontrol/app.go
> turn off grpc communication logging

- .github/workflows/stale.yml
180 is a bit too generous, most users stop answering if we pick it up again when we get to them.
> make stale shorter

- .github/workflows/test-integration-v2-TestNodeAdvertiseTagNoACLCommand.yaml
- .github/workflows/test-integration-v2-TestNodeAdvertiseTagWithACLCommand.yaml
- hscontrol/policy/acls.go
- integration/cli_test.go
> fix issue where advertise tags causes hang

- .github/workflows/test-integration-v2-TestEnableDisableAutoApprovedRoute.yaml
- hscontrol/db/routes.go
- hscontrol/poll.go
- integration/route_test.go
> ensure renabled auto-approve routes works

- hscontrol/db/node.go
> fix node expire error due to type in gorm model Update

- docs/oidc.md
> document setting oidc client secret cia env

- docs/running-headscale-linux-manual.md
Just small fix to copy-paste tutorial deploy
> Docs: fix path to nologin shell

- hscontrol/poll.go
Before this logged ~10 messages every few seconds and quite spamming the log.
> Reduce poll logging to debug

- .goreleaser.yml
> fix ifs in goreleaser gotemplate

- docs/running-headscale-linux.md
> Fix typo in docs - DB file path

- .github/workflows/docs.yml
> update docs workflow

- docs/faq.md
> docs: Add FAQ question about using the same machine as server and client

- hscontrol/db/db.go
- hscontrol/types/config.go
fix an error where all other fields in the IP migration was viped.
> fix ip migration

- docs/web-ui.md
Adding @GoodiesHQ UI to our docs/website.
> Add the headscale-admin UI to the docs

- .github/workflows/docs-test.yml
- docs/requirements.txt
I reckon we currently have the doc generation broken, add test to see.
> Add test stage to docs

- hscontrol/grpcv1.go
use errors.New to replace fmt.Errorf with no parameters will much better.
> chore: use errors.New to replace fmt.Errorf with no parameters will much better.

- hscontrol/app.go
This PR hangs the /debug/pprof handler in the debug router.
> Move pprof handler to metrics endpoint

- docs/index.md
- docs/running-headscale-linux-manual.md
- docs/running-headscale-openbsd.md
> fixed typo and path

- flake.nix
This seems to be missing from the flake: from dev shell I failed to run `make lint` without this.
Re: linting, there are several files reformatted: would you accept a reformatting PR for those + adding format check on CI? (Given that this will cause a lot of noise, you might prefer this to be a maintainer PR?)
<details>
<summary>list of files</summary>
- CONTRIBUTING.md
- cmd/headscale/cli/debug.go
- cmd/headscale/cli/nodes.go
- cmd/headscale/cli/preauthkeys.go
- cmd/headscale/cli/routes.go
- cmd/headscale/cli/utils.go
- cmd/headscale/headscale_test.go
- hscontrol/app.go
- hscontrol/auth.go
- hscontrol/auth_noise.go
- hscontrol/db/db.go
- hscontrol/db/ip.go
- hscontrol/db/ip_test.go
- hscontrol/db/node.go
- hscontrol/db/node_test.go
- hscontrol/db/routes.go
- hscontrol/db/routes_test.go
- …
> Add gofumpt to dev dependencies

- cmd/headscale/cli/nodes.go
- cmd/headscale/cli/utils.go
- hscontrol/oidc.go
- hscontrol/util/string.go
> remove custom contains funcs for slices.Contains

- hscontrol/derp/derp.go
- integration/embedded_derp_test.go
> test embedded derp with derp updater, check client health

- .coderabbit.yaml
Code Rabbit is one of these new fancy LLM code review tools. I am skeptical but we can try it for free and it might provide us with some value to let people get feedback while waiting for other people.
> add coderabbit config

- integration/auth_oidc_test.go
- integration/auth_web_flow_test.go
- integration/cli_test.go
Fixed integration tests with #2184
> Fixed loginUrl with "WithTLS()" used. Added "WithTLS()" to scenario integration tests

- CHANGELOG.md
- hscontrol/db/node.go
- hscontrol/db/node_test.go
- hscontrol/util/dns.go
- hscontrol/util/dns_test.go
> #2177 Added conversion of 'Hostname' to 'givenName' in a node with FQDN rules applied

- .github/CODEOWNERS
@nblock has contributed a great rewrite of the docs, this will empower to review changes to it and move faster.
This is pending him being added to the repo as a maintainer, the commit shows this error.
> add nblock to doc owners

- CODE_OF_CONDUCT.md
- README.md
- docs/about/faq.md
- docs/about/help.md
- docs/about/releases.md
- docs/index.md
- docs/ref/integration/web-ui.md
Replace channel links with links to discord invite link and remove channel list.
Fixes: #1521
Thx to @unusualevent for pointing this out!
---
> Use discord server invite link

- docs/ref/acls.md
- docs/usage/connect/apple.md
- docs/usage/getting-started.md
Small doc improvements brought up in recent issues or Discord.
Ref: #2238
> Misc doc fixes

- docs/requirements.txt
- mkdocs.yml
Simplifies/updates dependencies and fixes dependabot warnings.
> Documentation dependencies

- .github/workflows/docs-test.yml
- .github/workflows/docs.yml
> Bump deprecated github actions

- CHANGELOG.md
- Makefile
- config-example.yaml
> update oidc part of changelog for 0.24.0

- hscontrol/db/routes.go
- hscontrol/db/routes_test.go
- hscontrol/types/routes.go
> fix deletion of exit routes without nodes

- .github/workflows/test.yml
- hscontrol/oidc.go
- integration/auth_oidc_test.go
> Set CSRF cookies for OIDC

- hscontrol/types/users.go
- hscontrol/util/dns.go
> allow @ and Log if OIDC username is not consider valid

- hscontrol/oidc.go
> fix nil pointer deref

- CHANGELOG.md
- cmd/headscale/cli/routes.go
- hscontrol/db/db.go
- hscontrol/types/routes.go
> make it harder to insert invalid routes

- CHANGELOG.md
- hscontrol/app.go
> fix panic if derp update is 0

- hscontrol/db/users.go
> create and rename usernames validated by new func

- CHANGELOG.md
- docs/about/clients.md
- hscontrol/db/db.go
- hscontrol/notifier/notifier.go
- hscontrol/notifier/notifier_test.go
- hscontrol/policy/acls.go
- hscontrol/poll.go
- hscontrol/types/node.go
- hscontrol/util/dns.go
- integration/acl_test.go
- integration/auth_oidc_test.go
- integration/cli_test.go
- integration/dns_test.go
- integration/dockertestutil/network.go
- integration/dsic/dsic.go
- integration/hsic/config.go
- integration/hsic/hsic.go
- integration/ssh_test.go
- integration/tsic/tsic.go
- integration/utils.go
Replaces https://github.com/juanfont/headscale/pull/2380 as it went stale. Rebase + squash (kept @Nbelles as author, thx!)
> Spell check

- hscontrol/noise.go
> use tailscale version in all unsupported errs

- cmd/headscale/cli/nodes.go
- hscontrol/db/db.go
- hscontrol/routes/primary.go
Drop the route table and add some usage hints to the routes flag.
> Drop route table

- docs/about/faq.md
> Add a FAQ entry about two nodes seeing each other

- hscontrol/db/node_test.go
- hscontrol/policy/policy_test.go
- hscontrol/policy/v1/acls.go
- hscontrol/policy/v1/acls_test.go
- hscontrol/util/dns.go
- hscontrol/util/string_test.go
- integration/acl_test.go
- integration/cli_test.go
- integration/general_test.go
- integration/hsic/hsic.go
- integration/route_test.go
- integration/ssh_test.go
Make it so we dont have to write two docs, remove rewrite hack for integration test.
> allow users to be defined with @ in v1

- hscontrol/db/node.go
- hscontrol/types/node.go
- hscontrol/types/preauth_key.go
> code comment around tags

- docs/about/features.md
> Mention "Network flow logs" as a missing feature in the documentation

- cmd/headscale/cli/nodes.go
- gen/go/headscale/v1/node.pb.go
- gen/openapiv2/headscale/v1/headscale.swagger.json
- hscontrol/grpcv1.go
- integration/cli_test.go
- proto/headscale/v1/node.proto
> notify nodes after owner change

- hscontrol/policy/matcher/matcher.go
- hscontrol/policy/policy_test.go
> policy/matcher: fix bug using contains instead of overlap

- docs/setup/install/container.md
> [docs] Add quotes to docker run command to prevent word splitting

- .github/workflows/test-integration.yaml
- CHANGELOG.md
- hscontrol/mapper/mapper.go
- hscontrol/mapper/mapper_test.go
- hscontrol/mapper/tail.go
- hscontrol/mapper/tail_test.go
- hscontrol/notifier/notifier_test.go
- hscontrol/policy/matcher/matcher.go
- hscontrol/policy/pm.go
- hscontrol/policy/policy.go
- hscontrol/policy/policy_test.go
- hscontrol/policy/v2/policy.go
- hscontrol/types/node.go
- integration/control.go
- integration/hsic/hsic.go
- integration/route_test.go
> policy: reduce routes sent to peers based on packetfilter

- cmd/headscale/cli/root.go
> cli: policy check, dont require config or log

- CHANGELOG.md
> Add migration steps when policy is stored in the database

- .gitignore
- CHANGELOG.md
- docs/ref/configuration.md
Please see commit messages for details.
> Do not ignore config-example.yml, HEADSCALE_CONFIG, document breaking change

- hscontrol/tailsql.go
> Fix typo in TailSQL log

- docs/ref/integration/tools.md
This pull request updates the `docs/ref/integration/tools.md` file to expand the description of third-party tools and add a new entry to the list of related projects.
Documentation updates:
* Expanded the description to include "client libraries" in addition to tools and scripts related to Headscale.
* Added a new entry for `headscale-client-go`, a Go client implementation for the Headscale HTTP API.
> feat(tools): Add Go client implementation

- .github/ISSUE_TEMPLATE/bug_report.yaml
> Fix command in bug report template

- docs/about/faq.md
- docs/ref/oidc.md
Result of running [cspell](https://cspell.org/) on the docs directory using the following configuration file:
```json
{
"dictionaries": [
"en-gb",
"softwareTerms",
"companies",
"go"
],
"ignorePaths": [
"**/*.svg",
"**/*.yaml",
"**/*.yml"
],
"language": "en",
"words": [
"alpn",
"authelia",
"authentik",
"authkey",
"authurl",
"autocert",
"autogroup",
"autogroups",
"caddyfile",
"configtest",
"dalby",
"debugkey",
"derp",
"distroless",
"entra",
"headplane",
"headscale",
"headscalebacktosqlite",
"homelabbers",
"hosters",
"hscontrol",
"ingressgateway",
"juanfont",
"jumpcloud",
"kanidm",
"kristoffer",
"ldflags",
"letsencrypt",
"mkdocs",
"myexit",
"myfirstuser",
"myrouter",
"myvpn",
"netcheck",
"netmap",
"nologin",
"nonroot",
"noout",
"pacman",
"pkce",
"preauthkey",
"preauthkeys",
"setcap", …
```
> docs: fix typos

- CHANGELOG.md
- hscontrol/app.go
- hscontrol/handlers.go
I've added `/robots.txt` handler+endpoint, so to avoid crawlers (if they respect it). I was unsure of where to place the handler, and the endpoint logic, but I've just tried to group it together with others that seemed to make sense.
Should there be added any unit test/integration test for this change? My initial thought is no. But I'm uncertain if there are hard requirements for this, for any features :)
I'll add a changelog entry after this PR has been opened.
Fixes #2535
> feat: add robots.txt

- docs/setup/requirements.md
> Document ports in use

- derp-example.yaml
- docs/ref/derp.md
Add documentation for d29feaef.
Fixes: #2450
> Describe how to remove a DERP region

- docs/about/faq.md
> Add FAQ entry about the recommended upgrade path

- CHANGELOG.md
- docs/about/faq.md
- docs/ref/dns.md
Please see commit messages for details.
> Document how to recover from a policy error in the database
