juanfont/headscale

README.md
`s/headcale/headscale`
btw. I _like_ the name `headcale` better.
=> minor readme typo

cmd/headscale/headscale.go
Make headscale look for its config file in 
/etc/headscale
$HOME/.headscale
in addition to the current directory.
=> Add additional locations to look for the config.json file

cmd/headscale/headscale.go, config.json.example
If the configuration file contains relative paths (e.g. in the values for private_key_path or derp_map_path), interpret them as relative to the directory where the config.json file was read from.
=> Handle relative paths in private_key_path and derp_map_path

README.md, app.go, cmd/headscale/headscale.go, config.json.example, go.mod
Add supporrt for TLS to the web service (automatic with Let's Encrypt, or via externally managed certificate/key files). 
This PR als has a small bugfix for absPath, added error checking after calling the Serve() function, and a new configuration reference section in the README.md file.
=> Add support for TLS to the web service.

cli.go
* fix: remove db twice.
* better for new error, use errors.New.
* Error strings should not be capitalized or end with punctuation.
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
=> fix: remove db twice

Makefile, README.md, cmd/headscale/headscale.go, scripts/version-at-commit.sh
The default is 'build'. The build target calls the new version-at-commit.sh script which will automatically populate the version variable inside the Headscale binary.
Once we start tagging releases on the git tree, that will come in handy.
The Makefile also has a 'test' target (does nothing yet, no tests yet) and a 'dev' target, which runs linters, tests, and finally builds.
=> Add a Makefile with a few targets.

cli.go, cmd/headscale/cli/namespaces.go, cmd/headscale/cli/nodes.go, cmd/headscale/cli/preauthkeys.go, cmd/headscale/cli/routes.go, cmd/headscale/cli/server.go, cmd/headscale/cli/utils.go, cmd/headscale/headscale.go, routes.go
`cmd/headscale/headscale.go` was getting already a bit out of control. These commits changes a bit the structure for the sake of tidiness, but dumping into the `cli` package the CLI funcs.
=> Reorganise the CLI structure

README.md, cmd/headscale/cli/nodes.go, cmd/headscale/cli/preauthkeys.go, cmd/headscale/cli/routes.go, cmd/headscale/headscale.go
This PR changes how namespaces are specified in the commands of Headscale. Basically mimicking how `kubectl` behaves.
=> Namespace is now a flag for all the commands

README.md, api.go, cmd/headscale/cli/nodes.go, cmd/headscale/headscale.go
Implements #14 (need to add more info + json output, but basics are there). Also `register` cmd is now under `node` (I reckon makes more sense)
=> List nodes in namespace + register under node command 

Makefile, app.go, db.go, go.mod, go.sum, preauth_keys.go, preauth_keys_test.go
This fixes a bug in preauthkeys and adds tests. The tests use sqlite3.
=> Preauthkeys improvements

README.md, cli.go, cmd/headscale/cli/namespaces.go, cmd/headscale/cli/nodes.go, cmd/headscale/cli/preauthkeys.go, cmd/headscale/cli/routes.go, cmd/headscale/cli/utils.go, cmd/headscale/headscale.go, routes.go, utils.go
This series of commits add support for a basic JSON output in all the Headscale commands.
The structure of the JSON is veeeery subject to changes, but this should help with the development of integration tests + automating the deployments of headscale.
=> Added JSON-formatted output to CLI

app_test.go, cmd/headscale/cli/namespaces.go, cmd/headscale/headscale.go, namespaces.go, namespaces_test.go, preauth_keys_test.go
This also reorganizes the test infrastructure a bit, moving the shared functions to app_test.go
=> Add a DestroyNamespace command and tests for the Namespace functions.

README.md, api.go, app.go, cmd/headscale/cli/nodes.go, cmd/headscale/cli/preauthkeys.go, cmd/headscale/cli/server.go, cmd/headscale/cli/utils.go, cmd/headscale/headscale.go, config.json.postgres.example, config.json.sqlite.example, machine.go, machine_test.go, namespaces.go, namespaces_test.go, preauth_keys.go, preauth_keys_test.go, routes_test.go
Also add some tests for that feature.
Other fixes: clean up a few typos in comments. Fix a bug that caused the tests to run four times each. Be more consistent in the use of log rather than fmt to print errors and notices.
=> Add support for ephemeral nodes via a special type of pre-auth key.

api.go
As discussed in Gitter (https://gitter.im/headscale-dev/community?at=60a9618c801b07264e631b7f), there is some weirdness in how the tailscale clients first interact with the control server in the `/map` endpoint.
The client uses `tailcfg.MapRequest` to indicate the different stages of its startup process. At the beginning of the interaction, the client just expects an updated `tailcfg.DERPMap` - not the full list of its peers. It will close the connection as soon as it receives the first `tailcfg.MapResponse`.
With this PR headscale closes the connection when the client is expecting so, in these initial interactions to `/map`.  In these stages it does not start the keepAlives either.
I don't think this is completely solved, so I added a few more logging messages to track this.
=> Improving how headscale handles the client startup process

api.go
This commit changes a bit how we handle the registration workflow. Hopefully solves #32.
=> Handle client sending new NodeKey 

api.go
The issue occurs when a client closes the connection. We receive cancellation of the gin context here https://github.com/juanfont/headscale/blob/main/api.go#L322. Because of the `defer close(update)` in PollNetMapHandler we were closing the channel outside the mutex so it can happen that a new client arrives and tries to notify its peers - including the one that just closed the connection https://github.com/juanfont/headscale/blob/main/api.go#L288
Fixes #32.
=> Fix a race condition when a client closes the connection

.github/workflows/release.yml, .github/workflows/test.yml, .goreleaser.yml
For the time being only on new tags...
=> Use goreleaser to generate binary builds

cmd/headscale/cli/nodes.go
Fixes a nil pointer dereference observed when listing nodes that have
not yet connected.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb931a4]
goroutine 1 [running]:
github.com/juanfont/headscale/cmd/headscale/cli.glob..func8(0x13c93e0, 0xc0004c4220, 0x0, 0x2)
/go/src/headscale/cmd/headscale/cli/nodes.go:74 +0x364
github.com/spf13/cobra.(*Command).execute(0x13c93e0, 0xc0004c41e0, 0x2, 0x2, 0x13c93e0, 0xc0004c41e0)
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x13ca2e0, 0xc000497110, 0xe76416, 0x6)
/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...) …
```
=> Fix nil dereference in nodes list command.

api.go, app.go, app_test.go, cli.go, cli_test.go, db.go, go.mod, go.sum, machine.go, machine_test.go, namespaces.go, namespaces_test.go, preauth_keys.go, preauth_keys_test.go, routes.go, routes_test.go, utils.go
GORM 2.0, the ORM Headscale uses was fully rewritten for version 2.0, and includes breaking changes.
This series of commits change the codebase to depend on this new version. Nothing too fancy :)
=> Migrate to GORM 2.0

cmd/headscale/cli/namespaces.go, cmd/headscale/cli/nodes.go, cmd/headscale/cli/preauthkeys.go
Before this PR some commands in Headscale were plural (e.g. `routes`) while others were singular (e.g. `namespace`).
This single commit changes all the available commands into plural words.
=> Change all commands to plural words

api.go, app.go, app_test.go, cli.go, cli_test.go, db.go, machine.go, machine_test.go, namespaces.go, namespaces_test.go, preauth_keys.go, preauth_keys_test.go, routes.go, routes_test.go, utils.go
This commit changes the code to rely on a single DB object for Headscale, so Gorm can reuse the connections. 
When using Sqlite for long periods of time we would get an error on too many files open otherwise.
=> Use gorm connection pool

derp.yaml
The repo link referenced in derp.yaml is invalid and is missing the new DERP addresses.
This PR updates the file to use the newest tailscale DERP servers and updates the link in the comment.
Out of curiousity is `stunonly` always `false`, and `derptestport` always `0`?
`stunport`, `stunonly`, and `derptestport` have no references in the code so not sure if these fields are still needed.
=> Update DERP server definitions

api.go, app.go, machine.go, namespaces.go
This PR shows sends to the clients the namespace name in the same struct as Tailscale.com sends the user info, so when doing `tailscale status` the namespace is shown.
=> Improving namespace/user support 

README.md, app.go, cmd/headscale/cli/utils.go, cmd/headscale/headscale_test.go, config.json.postgres.example, config.json.sqlite.example
Currently the default (and non-configurable) Let's Encrypt listener will
bind to all IPs. This isn't ideal if we want to run headscale on a specific
IP only.
This also allows for one to set the listener to something other than
port 80. This is useful for OSs like OpenBSD which only allow root to
bind the lower port ranges (and don't have `setcap`) as we can now run
`headscale` as a non-privileged user while still using the baked in ACME
magic. Obviously this configuration would also require a reverse proxy
or firewall rule to redirect traffic. I attempted to outline that in the
README change.
=> Add a 'tls_letsencrypt_listen' config option

README.md, app.go
=> Add some more detail to the README about the different Let's Encrypt

cmd/headscale/cli/version.go, cmd/headscale/headscale.go
Move the versionCmd to it's own file in cmd/cli/.  To make code more clean and coherent. No functional impact on codebase.
=> Refactor cmdVersion to cli package

README.md, cmd/headscale/headscale_test.go, config.json.postgres.example, config.json.sqlite.example
We had :8000 in the examples, while the Dockerfile and Kubernetes YAMLs use :8080. 
This PR changes everything to :8080, as it is the port that had actually running software pointing at it.
This fixes #68.
=> Use 8080 as default port in the example config

app.go, db.go, machine.go, machine_test.go, namespaces.go
The in-memory `clientsPolling` map is only available from the Headscale process serving the API. This means that some changes performed by the CLI (which is a different process) are not propagated immediately to the polling clients. 
This is what is happening in #52. Nodes are successfully removed from the DB, but the connected machines do not receive an updated node `Map` until their client decides to close the long poll and reconnect. 
I have added a new worker that polls the KV table we had since the beginning in Headscale DB schema. Namespaces whose nodes should be sent an updated map are added to the `namespaces_pending_updates` key. 
The hardcoded polling time is 5000 msecs.
=> Added communication between Serve and CLI using KV table 

README.md, acls.go, api.go, app.go, cmd/headscale/cli/root.go, cmd/headscale/cli/utils.go, cmd/headscale/headscale.go, go.mod, go.sum, machine.go, namespaces.go
This PR migrates from the built in Go logger to a structured logger ([zerolog](https://github.com/rs/zerolog)).
This allows us to:
- Make loglevels user configurable
- Add loads of trace and debug logging to help developer, but not bother users
- Type safe fields in each log entry
- Enforce some structure and consistency on log messages
Please note, this does not change or override Gin's logger, only the internal one.
example:
=> Switch to a structured logger

README.md, acls.go, api.go, app.go, cmd/headscale/cli/root.go, cmd/headscale/cli/utils.go, cmd/headscale/headscale.go, go.mod, go.sum, machine.go, namespaces.go, routes.go
This PR depends on (or contains if you like) #74, please review that first and merge that / or just merge this when both are reviewed.
This PR removes most of the locks in the PollingMap handler as there
was combinations that caused deadlocks. Instead of doing a plain map and
doing the locking ourselves, we use sync.Map which handles it for us.
This should resolve #56 #50 and #73
=> Fix deadlock issue

cmd/headscale/headscale.go, go.mod, go.sum
This commit tries to detect if users can render colors in their terminal
and only enables color logs if that is true.
It also adds no-color.org's NO_COLOR env var support to allow it to be
disabled.
=> Try to detect color support, make color configurable

api.go, app.go, routes.go
This PR removes more deadlocks, one I forgot and on (from keepAlive) that I could not understand why was there.
Ideally we need some wireup tests to test for locks and check actual tailscale(d) behaviour over time.
=> Remove more deadlocks

cmd/headscale/cli/preauthkeys.go, preauth_keys.go, preauth_keys_test.go
As pointed out in #78, we can't delete a preauthkey. This PR implements a similar functionality, by marking a preauthkey as expired.
=> Add CLI command to mark preauthkeys as expired

app.go, cmd/headscale/cli/server.go, machine.go, namespaces.go
As reported by @viq on Twitter, ephemeral nodes are being deleted, but the changes are not notified to their former peers. 
This PR addresses that.
=> Also notify peers when deleting ephemerals

.dockerignore, api.go, app.go, go.mod, go.sum, integration_test.go, machine.go, namespaces.go, poll.go, routes.go, utils.go
This PR adds several more integration tests with `Tailscale`, and tries to resolve some of the issues that arise from this in `PollNetMapHandler`:
- Integration test ensuring all Nodes are present in each note `tailscale status` output
- Integration test pinging all nodes from all nodes (cross-ping)
These test will mostly pass, however, there is still some timing and/or race conditions preventing them from being completely reliable. This will be work for the future now that we have a reference to compare against.
The integration tests has switched from gocheck to [testify](https://pkg.go.dev/github.com/stretchr/testify/suite?utm_source=godoc#pkg-overview), as they provide a much richer test setup (and most importantly allow for sub-tests in for loops)
When setting up five tailscale nodes …
=> Improve reliability of PollMapHandler, more integration tests

cmd/headscale/cli/routes.go, routes.go, routes_test.go
This commit rewrites the `routes list` command to use ptables to present
a slightly nicer list, including a new field if the route is enabled or
not (which is quite useful).
In addition, it reworks the enable command to support enabling multiple
routes (not only one route as per removed TODO). This allows users to
actually take advantage of exit-nodes and subnet relays.
=> Enhance route command with ptables and multiple routes

.github/workflows/lint.yml
This commit splits the lint and test steps into two different jobs in
github actions.
Consider this a suggestion, the idea is that when we look at PRs we will
see explicitly which one of the two types of checks fails without having
to open Github actions.
=> Split lint and test CI files

.github/workflows/test-integration.yml, .gitignore, api.go, app.go, cmd/headscale/cli/utils.go, integration_test.go, integration_test/etc/config.json, machine.go, poll.go
This PR is a two parter:
- Hook up the integration tests
- Checking that all nodes is a part of the `tailscale status` of all other nodes
- Ping all nodes from each node directly
- Fix the issues making the integration tests fail
This PR addresses a series of issues with the update logic making us able to ensure that nodes stay up to date when the network mesh changes. Previously it managed to push out changes sporadically and not consistently. 
This is done by:
- Ensuring updates are issued on omitPeer=true, stream=false (nodes use that to update their addresses)
- Ensure the update channel actually is consumed by the stream function
- Periodically issue an update request to all nodes
In addition, to not send excess amount of traffic to all nodes with unnecessary update, a simple "state" …
=> Improve logic to keep nodes up to date with the network state

Makefile, scripts/version-at-commit.sh
Make version-at-commit.sh work on systems that don't have bash in `/bin/bash` while here.
=> Fix setting of version

derp.yaml
The official doc is hidden under a bunch of issues. Add a doc link here and hope it could be helpful.
=> docs: add notes on how to build own DERP server

cmd/headscale/cli/nodes.go
fix #90 
I think we should add something like `golangci-lint` to do some lint.
=> fix: check last seen time without possible null pointer

cmd/headscale/headscale.go
Currently there is a warning for every command run when NO_COLOR is set. For example:
```
$ headscale nodes 
{"level":"trace","time":"2021-09-12T07:31:48-06:00","message":"NO_COLOR is set, disabling colors"}
Manage the nodes of Headscale
Usage:
headscale nodes [command]
Available Commands:
delete      Delete a node
list        List the nodes in a given namespace
register    Registers a machine to your network
share       Shares a node from the current namespace to the specified one
Flags:
-h, --help               help for nodes
-n, --namespace string   Namespace
Global Flags:
-o, --output string   Output format. Empty for human-readable, 'json' or 'json-line'
Use "headscale nodes [command] --help" for more information about a command.
$
```
This disables that.
=> Remove trace lines about NO_COLOR.

Dockerfile.tailscale, integration_test.go
This PR expands the integration tests:
- Tailscale version support (list with available versions in apt)
- Stability and neating up a bit (use json output and proper datatypes)
- Initial support for testing shared nodes (no ping yet)
=> Improve integration tests

README.md
The instructions in README.md were missing the `namespaces` part of the command.
=> Fix namespace instructions in README.md

Makefile, cmd/headscale/cli/version.go, cmd/headscale/headscale.go, go.mod, go.sum
This small PR just adds an updated version checker on startup. 
It uses https://github.com/tcnksm/go-latest to fetch the latest release in GitHub.
=> Added version checker on Headscale startup

app.go, cmd/headscale/cli/utils.go, config.json.postgres.example, config.json.sqlite.example
I tested with BuyPass using the following conf values:
```
"acme_email": "aaron@REDACTED",
"acme_url": "https://api.buypass.com/acme/directory",
```
=> Add the ability to specify the directory URL used for ACME.

.goreleaser.yml
building the headscale executable.
The goreleaser builds we re not populating the headscale version (accessible via `headscale version`) properly, because the flag wasn't set correctly. This commit fixes that.
=> Make sure that goreleaser uses the appropriate version string when

README.md
Would this be a good documentation improvement as discussed in #58 ?
=> Document client OS support in a table

.github/workflows/release.yml
Seeing that arm64 builds of CLI are already implemented ( #168 ), this adds arm64 arch digests to the Release image.
Also, I'm adding cache for the build layer to speed up the deployment. 
Loving your work!
Will upload a Helm chart as soon as I understand DERP systems.
=> arm64 docker image build in release process

docs/Running.md
* This would cause otherwise the command to abort after the first statement of the docker command ;)
=> Running.md: fix missing backslash (\)

cmd/headscale/cli/preauthkeys.go, integration_cli_test.go
When creating a preauthkey, the default expiration was passed through as a nil value, instead of the default value (24h). This resulted in the preauthkey being created with expiration key '0001-01-01 00:00:00', which meant the key would not work, because it was already expired.
This commit applies the default expiration time (24h) when a preauthkey is created without a specific expiration. It also updates an integration test to make sure this bug does not reoccur.
=> Fix default preauthkey expiration

.goreleaser.yml
This small PR adds allows to get a release tagged as prerelease if we include in the tag stuff like -rc1
=> Enable marking releases as prerelease

api.go, apple_mobileconfig.go, oidc.go, swagger.go
This pull request fixes a number of template errors resulting in XSS vulnerabilities.
I recommend creating a [GitHub security advisory](https://docs.github.com/en/code-security/security-advisories/creating-a-security-advisory) with the following:
* Affected product
* Ecosystem: `Go`
* Package name: `github.com/juanfont/headscale`
* Affected versions: unknown
* Patches versions: TBD
* Severity: `Assess severity using CVSS`
* Vector string: `CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:L/I:L/A:N`
* CWE: [74](https://cwe.mitre.org/data/definitions/74.html)
* CVE identifier: `Request CVE ID later`
* Title: `Unsanitized HTML Template Evaluation`
* Description:
If the Tailscale client were to be compromised, it could instruct users to go to
a malicious URL where said client has **total** control over …
=> Template Fixes

go.mod, go.sum
Just two minor updates in the libs, reported by Github's Dependabot.
=> Minor security updates in go.mod

.github/workflows/build.yml, .github/workflows/test-integration.yml, .github/workflows/test.yml, Dockerfile, Dockerfile.alpine
With this PR the binary is compiled with go 1.17.6 to close some of the open CVE´s in go 1.17.1. 
Furthermore the resulting binary is stripped which reduces the size of the binary by ~10MB.
```
before:
-rwxr-xr-x    1 root     root      32766008 Jan 13 16:07 /bin/headscale
after:
-rwxr-xr-x    1 root     root      22325232 Jan 14 08:14 /bin/headscale
```
=> Strip binary, update to go-1.17.6

poll.go
This PR adds a missing `return` statement in the `PollNetMapHandler` method.
=> Fix missing return in PollNetMapHandler

.github/workflows/lint.yml, app.go
This PR removes potential whitespace from the private key before we try to unmarshal it. It helps us deal with issues were e.g. secrets management systems add a new line.
Fixes #287
=> Trim whitespace from privateKey before parsing

CHANGELOG.md, machine.go, poll.go
- ~~raised a GitHub issue or discussed it on the projects chat beforehand~~ - found existing issues.
- ~~added unit tests~~ - testing requires a client, currently only available in integration tests.
- ~~] added integration tests~~
- updated documentation if ~~needed~~ - PR contains changes without changes to expected behaviour towards clients or users.
Fixes #232 (manually tested in the no-preauthkeys case)
Related to #93
=> PollNetMapStream: do not create any rows during long-poll operation

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/test-integration.yml, .github/workflows/test.yml
This commit configures the CI to run specific parts of the CI when
relevant changes has been made.
This should help us not have to deal with the integration tests when we
do doc/admin changes.
=> Set up build avoidance

db.go
The automatic migration did not pick up this change and it breaks
current setups as it only adds a new field which is empty.
This means that clients who dont request a new IP will not have any IP
at all.
=> Migrate ip_address field to ip_addresses

docs/running-headscale-linux.md
Headscale commands fail when running them as the current user instead of the user defined in the systemd file. This note provides 2 methods of how to correctly run the headscale commands.
=> Note when running as another user in systemd

.golangci.yaml, CHANGELOG.md, acls.go, acls_test.go, api.go, dns.go, docs/README.md, docs/acls.md, machine.go, machine_test.go, poll.go, utils.go
This PR is a first implementation of what has been discussed on #311 It should be reviewed commit by commit since last commits are linting modifications and changes quite much some part of the code that I didn't touch.
All subject discussed in PR #311 are not implemented here. I think all those modifications should be splitted in multiple PRs.
If this PR is too big, some commits could be moved outside of this PR it's related but just fixes some bugs on the ACLs parsing behavior.
=> Improvements on the ACLs and bug fixing

machine.go
After some more tests in tailscale I couldn't replicate the behavior
described in there.
When adding a rule, allowing A to talk to B the reverse connection was
instantly added to B to allow communication to B.
The previous assumption was probably wrong.
=> fix(machine): remove comment

CHANGELOG.md, acls.go, acls_test.go, acls_types.go, config-example.yaml, tests/acls/acl_policy_basic_wildcards.yaml, utils.go
=> Add YAML support to ACLs

acls.go
logs looks like the following
```
2022-03-02T20:43:08Z DBG Expanding alias=app-test
2022-03-02T20:43:08Z DBG Expanding alias=kube-test
2022-03-02T20:43:08Z DBG Expanding alias=test
2022-03-02T20:43:08Z WRN No IPs found with the alias test
2022-03-02T20:43:08Z DBG Expanding alias=prod
2022-03-02T20:43:08Z WRN No IPs found with the alias prod
2022-03-02T20:43:08Z DBG Expanding alias=prod
2022-03-02T20:43:08Z WRN No IPs found with the alias prod
```
fixes #383
maybe related to issue reported on discord on ACLs that weren't parsed properly
=> feat(acls): add some logs and skip error

config-example.yaml
Fixed typo in example config comment. Closes #386.
```
TLS_ALPN-01 => TLS-ALPN-01
```
=> docs: fix typo in ACME challenge type comment

CHANGELOG.md, acls.go, api.go, namespaces.go, namespaces_test.go, oidc.go, poll.go
This will fix #363 by applying normalization on the hostname. This normalization function will lowercase capital letters and replace forbidden chars. If it cannot find a solution it will raise an error on headscale server.
```
CAPITALNAME => capitalname
HOST Name 1 => host-name-1
```
=> Fix magic dns and uppercase letters

docs/running-headscale-container.md, docs/running-headscale-linux.md
Fixed docs `/metrics` default endpoint `8080 → 9090`.
Reference [`config-example.yaml`](https://github.com/juanfont/headscale/blob/1579ffb66ad3da3e76ea920734f78886405aac66/config-example.yaml#L23):
```
#
metrics_listen_addr: 127.0.0.1:9090
```
Verify `headscale` is available:
```shell
curl http://127.0.0.1:9090/metrics
```
=> Fixed docs metrics default endpoint

app.go, cmd/headscale/cli/utils.go, config-example.yaml, derp_server.go, integration_test/etc_embedded_derp/config.yaml
This commit also allows to set an external STUN server, while running the embedded DERP server (without embedded STUN)
=> Make STUN run by default when embedded DERP is enabled

derp.go
There is a possible nil pointer dereference panic in the `Headscale.scheduledDERPMapUpdateWorker`. Such as when the embedded DERP server is disabled.
=> fix: possible panic in `Headscale.scheduledDERPMapUpdateWorker`

CHANGELOG.md, Dockerfile.tailscale, Dockerfile.tailscale-HEAD, integration_cli_test.go, integration_common_test.go, integration_embedded_derp_test.go, integration_test.go
In preparation for the implementation of the new TS2021 protocol (Tailscale control protocol v2) we are expanding the test infrastructure
=> Add Tailscale unstable channel and repo HEAD to integration tests

CHANGELOG.md, api.go
I fat-fingered an auth-key, and observed this error:
```
2022-03-21T02:57:35Z INF New machine machine=localhost-live
2022-03-21T02:57:35Z DBG Processing auth key for localhost-live func=handleAuthKey machine=localhost-live
2022-03-21T02:57:35Z ERR ../home/runner/work/headscale/headscale/api.go:544 > Failed authentication via AuthKey error="AuthKey not found" func=handleAuthKey machine=localhost-live
2022-03-21T02:57:35Z ERR ../home/runner/work/headscale/headscale/api.go:567 > Failed authentication via AuthKey func=handleAuthKey machine=localhost-live
[GIN-debug] [WARNING] Headers were already written. Wanted to override status code 401 with 500
2022/03/21 09:57:35 [Recovery] 2022/03/21 - 09:57:35 panic recovered:
POST /machine/snip.machine.key HTTP/1.0
Host: snip-host
Connection: close …
```
=> Fix labels cardinality error when registering unknown pre-auth key

cmd/headscale/cli/api_key.go, cmd/headscale/cli/preauthkeys.go
The `-e` option for `preauthkeys create` and `apikeys create` is processed with `time.ParseDuration` which does not support the `d` suffix (for days) and also no other "bigger" suffixes:
* https://pkg.go.dev/time#ParseDuration
* https://github.com/golang/go/issues/11473
First I thought I could fix the CLI code but as it's just using cobra to read the expiration flag, I changed the documentation for the commands accepting the `-e` flag.
=> fix: Remove days from expiry option value examples

docs/running-headscale-linux.md
=> Fix wrong metrics port in docs

derp-example.yaml
=> Fix key name about derp port in derp-example.yml

CHANGELOG.md, poll.go
This commit fixes the issue of headscale crashing after sending on a
closed channel by moving the channel close to the sender side, instead
of the creator. closeChanWithLog is also implemented with generics now.
Signed-off-by: Moritz Poldrack <git@moritz.sh>
Fixes #342
=> fixed the issue of sending on closed channel

.gitignore, README.md, docs/README.md
The current link grants temp memberships which means people loose the server.
=> Update discord link so it does not grant temp memberships

CHANGELOG.md, app.go
`setLastStateChangeToNow` was being called everytime we run `expireEphemeralNodesWorker`, even if there are no nodes to expire.
=> Do not setLastStateChangeToNow every expireEphemeralNodesWorker call

app.go, derp_server.go, integration_test.go
As per https://github.com/juanfont/headscale/issues/567, I am temporarily reducing a bit the number of containers run in the integration tests.
This should make a little bit less of a PITA running the continuous integration
=> Reduce the number of containers in integration tests

CHANGELOG.md, app.go, cmd/headscale/cli/utils.go, config-example.yaml, oidc.go, utils.go
Adds knobs to configure three aspects of the OpenID Connect flow:
* Custom scopes to override the default "openid profile email".
* Custom parameters to be added to the Authorize Endpoint request.
* Domain allowlisting for authenticated principals.
* User allowlisting for authenticated principals.
=> Allow more configuration over the OIDC flow

CHANGELOG.md, api.go, app.go, cmd/headscale/cli/utils.go, cmd/headscale/headscale_test.go, config-example.yaml
This PR allows users to disable logtail in their Tailscale clients, essentially allowing them to stop sending logs to Tailscale.
This resolves #552.
LogTail is now disabled by default.
=> Allow headscale to enable/disable logtail

cmd/headscale/cli/api_key.go, cmd/headscale/cli/preauthkeys.go
Use the duration parser from the Prometheus project, this allows us to use `d`, `w` and `y`.
This fixes #322
=> Use Prometheus duration parser 

acls.go, acls_test.go
Basically always check whether a tag is forced instead of just on tagOwners failure. Also replace loops with contains.
=> Fix forced Tags with legitimate tagOwners

CHANGELOG.md, app.go, cmd/headscale/cli/utils.go, utils.go
This PR partially resolves https://github.com/juanfont/headscale/issues/173, allowing the users to send a reload signal (SIGHUP) to headscale to reload the ACL policies.
In addition, sending a SIGTERM, SIGINT etc, will now attempt to shutdown headscale gracefully.
=> Allow ACLs to be reloaded with SIGHUP

api_key.go
One of the glory enhancements of go-1.18 was the introduction of `strings.Cut` which reduces the burden of counting the length of the result slice, also makes code much more readable in such cases where only two results are expected.
=> Use strings.Cut to simplify logic

app.go, namespaces.go
This PR makes the setLastStateChangeToNow function take a list of
namespaces instead of a single namespace. If no namespaces is passed,
all namespaces will be updated. This means that the argument acts like a
filter.
Update the nodes after we have reloaded the ACL policy with sighup
=> Update all nodes after ACL has been reloaded with sighup

CHANGELOG.md, acls.go, acls_test.go, acls_types.go, docs/acls.md, machine_test.go, tests/acls/acl_policy_1.hujson, tests/acls/acl_policy_basic_1.hujson, tests/acls/acl_policy_basic_groups.hujson, tests/acls/acl_policy_basic_namespace_as_user.hujson, tests/acls/acl_policy_basic_protocols.hujson, tests/acls/acl_policy_basic_range.hujson, tests/acls/acl_policy_basic_wildcards.hujson, tests/acls/acl_policy_basic_wildcards.yaml, tests/acls/acl_policy_invalid.hujson
Implements #617.
Tailscale has changed the format of their ACLs to use a more firewall-y terms ("users" & "ports" -> "src" & "dst"). They have also started using all-lowercase tags. 
Also, protocol filtering support :)
This PR implements these changes.
=> Update ACL syntax and add support for protocol filtering

CHANGELOG.md, api.go, cmd/headscale/headscale_test.go, config-example.yaml, config.go, integration_test/etc/alt-config.dump.gold.yaml, integration_test/etc/config.dump.gold.yaml
This allows tailscaled to pick a random udp port and lets direct connections succeed for broken fortinet enterprise firewalls.
https://tailscale.com/kb/1181/firewalls/
=> Add ability to set randomizeClientPort

CHANGELOG.md, cmd/headscale/cli/utils.go, config.go
This fixes #251 
This PR will:
- Move the configuration check for `ephemeral_node_inactivity_timeout` to where it should be
- Set a default for `ephemeral_node_inactivity_timeout`
- Add a warn if configuration could not be found.
=> Fix obtuse "ephemeral_node_inactivity_timeout" error

utils.go, utils_test.go
Introduced by random node suffix: GenerateRandomStringDNSSafe will panic occasionally if the random base64 string contains too many - and _ due to the replacement. Fix by looping.
=> Fix occasional panic on registration

CHANGELOG.md, machine.go
Nodes were permantly shown offline because we are not sending the `Online` field of Node. Even when we are communicating from another client.
This commit fixes it based on LastSeen with keepAliveInternal. Simple :)
=> Send Online field of tailcfg.Node based on LastSeen

CHANGELOG.md, app.go
Does not fix broken graceful shutdown, but does limit it with a timeout which prevents sigkill by a service manager on stop.
Also close db connections explicitely to allow running queries to complete.
=> add timeout for http shutdown, add db disconnect

cmd/headscale/cli/utils.go
When we pass `--output json` or similar we suppress all the logs -which also deactivates the call to `os.Exit` when doing Fatal().
This is a quick fix for #652.
=> Quick fix to segfault on CLI when Headscale is not running

.github/workflows/test-integration.yml, integration_cli_test.go, integration_common_test.go, integration_embedded_derp_test.go, integration_test.go
This PR aims to harden the integration tests a bit so they can be rerun in the same environment on failure. In addition, we will let them rerun 5 times to try to allow us to not have to pay attention to them and rerun manually.
It should also make them a bit more consistent when running locally.
=> Make integration tests retry on failure.

CHANGELOG.md, config-example.yaml, config.go, integration_test/etc/alt-config.dump.gold.yaml, integration_test/etc/alt-config.yaml, integration_test/etc/config.dump.gold.yaml, integration_test/etc/config.yaml, integration_test/etc_embedded_derp/config.yaml, poll.go
A user with >150 machines in their tailnet reported high CPU consumption. Although for sure we have other bottlenecks, a 10 second check interval for updates might be a bit too much.
This PR allows an advanced user to change this (until now hardcoded) setting.
=> Make tailnet updates check interval configurable

CHANGELOG.md, app.go, flake.nix, go.mod, go.sum
=> remove gin completely, ~2MB reduction on final binary

CHANGELOG.md, app.go
This PR fixes a regression introduced in the HTTP API (fixes #681), when migrating out of Gin.
=> Fix API router

app.go, config.go, oidc.go, poll.go
There's few problems with a graceful shutdown that i tried to fix with this PR.
1. `shutdownChan` channel that was used to finish `PollNetMapStream` didn't work if no `PollNetMapStream` was running at the time of shutdown. Also, it could stop only single `PollNetMapStream` routine, as single value was passed to channel instead of closing it.
2. There is a race condition with function that handles termination signals, as it isn't included in an error group.
=> graceful shutdown fix

api.go, app.go, db.go
Add basic db check to health endpoint
=> ping db in health check

flake.nix, go.mod, go.sum
Dependabot notified of two Medium security vulnerabilities in github.com/opencontainers/runc. This PR fixes that.
=> Update runc dependencies to fix security notification

grpcv1.go, grpcv1_test.go, integration_cli_test.go, machine.go, machine_test.go
As mentionned on discord by @linksysrouter, there was a possibility to add multiple times the same tags. This PR should remove this.
=> Remove duplicate tags if sent by the client

app_test.go, cmd/headscale/headscale_test.go, derp.go, integration_embedded_derp_test.go, integration_general_test.go
io/ioutil is deprecated since go1.16. 
This PR removes it.
=> Replaced legacy ioutil usage

CHANGELOG.md, api.go, app.go, cmd/headscale/cli/nodes.go, grpcv1.go, machine.go, oidc.go
This PR lays the groundwork for the implementation of the TS2021 protocol (Tailscale control v2).
Under the Noise protocol the NaCl boxes encrypted with the `MachineKey` are dropped in favour of Noise sessions. `MachineKey` loses importance across the code base, and when using Noise they are not sent at all.
In headscale we were using the stripped version of the public MachineKey as a sort-of ID, for the iterative login process (including the registrationCache used in the web+CLI and the OIDC flows).
This PR addresses that, switching to NodeKey as identifier. 
In addition to it, it also improves a bit the handling of the registration process (and reduces the impact caused by #727 (although does not fully resolve it).
=> Improve registration protocol implementation and switch to NodeKey as main identifier 

api.go
This PR fixes a minor bug introduced in https://github.com/juanfont/headscale/pull/725, where the URL to register again an expired node is set with the old MachineKey-based param.
=> Fix expired node registration URL

CHANGELOG.md, app.go, config-example.yaml
=> Add ability to connect to PostgreSQL via unix socket

CHANGELOG.md, oidc.go
Fixes a bug introduced in https://github.com/juanfont/headscale/pull/685
=> Fix error decoding OIDC claims (#744)

CHANGELOG.md, app.go, config-example.yaml, config.go
=> feat: add support for TLS with Postgres

CHANGELOG.md, api.go, machine.go
Fixes the CLI registration of machines already present in DB:
* Machines that logged out were not added to registration cache when joining again
* If the machine was still in cache (<15min after the first registration), expiry was not updated
* Registration cache was not cleaned up after successful machine registration
Checks that the machine is registered with the right namespace
Fixes #522
=> Fix cli registration of expired machines

integration_common_test.go
Tailscale has just released v1.30.0 https://tailscale.com/changelog/#2022-08-31-client
This is the first Tailscale version where Headscale will offer the TS2021 protocol.
And it seems to work in my dev env :)
=> Add Tailscale v1.30.0 to the integration test roaster

.github/workflows/release.yml, .goreleaser.yml, CHANGELOG.md, Dockerfile, Dockerfile.alpine, Dockerfile.debug, docs/running-headscale-openbsd.md, go.mod
Tailscale v1.30+ requires Go 1.19 for us to be able to import it.
This PR switches Headscale to Go 1.19, as a prerequisite for a PR moving use towards their latest version.
=> Target Go 1.19 for Headscale

flake.lock, flake.nix
This PR switches our target for Nix to Go 1.19 - required for Tailscale 1.30.
=> Switch to Nix unstable for Go 1.19

.github/workflows/lint.yml, acls_test.go, api.go, app.go, config.go, db.go, derp.go, derp_server.go, machine_test.go, noise.go, oidc.go, protocol_common.go, protocol_common_poll.go, protocol_common_utils.go, protocol_legacy_poll.go, protocol_noise_poll.go
The move to Go 1.19 has broken golanglint, as the current version we use does not support 1.19.
Upgrading to golanglint-ci v1.49.0 brings new linters and strictness (is this a word?). This PR does the switch and fixes some stuff the new linter points out.
=> Fix linting broken after Go 1.19

CHANGELOG.md, derp_server.go, noise.go
TS2021 absolutely requires to have WebSockets proxified to Headscale if running it behind a reverse proxy. 
Although we do not support reverse proxy-ed setups, giving a hint in the logs will result in less issues opened (like #775).
=> Warn when Headscale is running behind an improperly configured proxy

docs/running-headscale-container.md
It appears to be causing confusion for users on Discord when copying/pasting from the example here, if Headscale crashes on launch then the container will be removed and logs can't be viewed with `docker logs`.
=> Remove --rm flag from Docker example

CHANGELOG.md, machine.go
This PR fixes (slightly hacky) an issue where subnet routers dont work as we dont pass the PrimaryRoutes parameter.
=> Fix subnet routers

CHANGELOG.md, app.go, config-example.yaml, config.go, integration_test/etc/alt-config.dump.gold.yaml, integration_test/etc/alt-env-config.dump.gold.yaml, integration_test/etc/config.dump.gold.yaml, protocol_common.go
OIDC might be configured, but unable to be initialised, this only runs
the oidc cycle if it is actually successfully set up/initialised.
Fixes #827 
=> Add option to allow headscale to start if OIDC fails to initialise

flake.lock, flake.nix
This might fix the listening issue due to newer go? and building of `buf` on macOS.
=> Nix update and format flake file

app.go
=> Move lets enc listener into go routine

Makefile, cmd/headscale/cli/mockoidc.go, flake.nix, integration_cli_test.go, integration_common_test.go, integration_embedded_derp_test.go, integration_general_test.go, integration_oidc_test.go, integration_test/etc_oidc/base_config.yaml
=> Run integration tests inside docker, dont depend on local platform

docs/running-headscale-container.md
As indicated by the comment, the default /var/lib/headscale path is not writable in the container. However the sample setting is not following that like `private_key_path`
None of above applies as it's just a simple typo fix.
=> Fix the proposed noise private_key_path

integration/control.go, integration/general_test.go, integration/hsic/hsic.go, integration/scenario.go, integration/tailscale.go, integration/tsic/tsic.go
=> Integration test v2, hostname ping test

.github/workflows/test-integration-cli.yml, .github/workflows/test-integration-derp.yml, .github/workflows/test-integration-general.yml, .github/workflows/test-integration-oidc.yml, .github/workflows/test-integration-v2-general.yml
The retry has no real function as it will just fail on "container exists" on the old tests and the new test will just try forever before it eventually fails.
=> Integration, remove retry

Makefile
=> Remove verbose flag for v2 tests, increase timeout

Makefile, integration/general_test.go, integration/tsic/tsic.go
=> Integration v2: port resolve magicdns

Makefile
These tests are "safe" to run in parallel, currently only CLI is marked for this, and it speeds them up quite a bit.
=> Run more tests in parallel

.goreleaser.yml, CHANGELOG.md, Dockerfile, Dockerfile.debug, Makefile, app.go, flake.nix, handler_legacy.go, handler_placeholder.go, protocol_legacy.go, protocol_legacy_poll.go
This commit starts an experiment to disable TS2019 (we also call it
legacy).
The two main goals for this right now is:
- Diasble TS2019, and verify that the integration test clients with the
appropriate TS2021 support works as expected
- Get an overview of how coupled the protocol code is, if this is easy,
it will be easy to remove when the time comes.
Also, users with "crazy" desires like only supporting the most modern
protocol _can_ build this version.
=> Add build flag to enable TS2019

protocol_common.go
When register with pre-auth key, headscale doesn't provide `LoginName` which is needed by `tailscaled.state`.
So it has to execute `tailscale up` twice to fetch the property.
```json
{
"ControlURL": "",
"RouteAll": false,
"AllowSingleHosts": true,
"ExitNodeID": "",
"ExitNodeIP": "",
"ExitNodeAllowLANAccess": false,
"CorpDNS": false,
"RunSSH": false,
"WantRunning": true,
"LoggedOut": false,
"ShieldsUp": false,
"AdvertiseTags": null,
"Hostname": "",
"NotepadURLs": false,
"AdvertiseRoutes": [],
"NoSNAT": false,
"NetfilterMode": 2,
"Config": {
"PrivateMachineKey": "privkey:0",
"PrivateNodeKey": "privkey:0",
"OldPrivateNodeKey": "privkey:0",
"Provider": "",
"LoginName": ""
}
```
=> Provide LoginName when registering with pre-auth key

app.go
In [NewHeadscale](https://github.com/juanfont/headscale/blob/main/app.go#L131) function exported constant errors are used in case of private key problems. They overshadow lower level errors that happen during reading/creation of private keys.
It's probably safe to assume that function `NewHeadscale` is not used in other packages. So missing constant errors shouldn't be a big problem for a users(otherwise it can be fixed with a little bit hacky error's `Is` implementation on the user side). On the other hand, overshadowing lower level errors can be a problem for debugging when running Headscale server(which will be more common problem).
=> Remove private key constant errors from NewHeadscale

.golangci.yaml, integration/scenario.go, integration/tailscale.go, integration/tsic/tsic.go
This small PR adds a WaitForReady method in the Tailscale interface for the integration tests. 
This is used after `tailscale up` to make sure that the clients are ready.
=> Add WaitForReady in TSIC

integration/general_test.go, integration/tailscale.go, integration/tsic/tsic.go
This PR extends the Tailscale interface to support running `tailscale up` and returning the result (ie. the login URL)
=> Extend TSIC integration interface for non-authkey logins

cmd/headscale/cli/nodes.go, integration/auth_web_flow_test.go, integration/hsic/hsic.go
This PR adds integration test coverage for the web auth (`tailscale up` + headscale register cmd).
If extends the scenario interface to handle the registration, parsing the URL headscale exposes.
=> Add Web auth integration tests (v2)

integration/auth_web_flow_test.go, integration/cli_test.go, integration/control.go, integration/general_test.go, integration/hsic/hsic.go, integration/integrationutil/util.go, integration/scenario.go, integration/scenario_test.go, integration/tsic/tsic.go
This commit injects the per-test-generated tls certs into the tailscale container and makes sure all can ping all. 
It adds several other helper functions
=> Make TLS setup work automatically

oidc.go
This PR improves the handling on NodeKeys in the OIDC auth flow + adds more logging and checks.
=> OIDC code cleanup and harmonize with regular web auth

integration/scenario.go
Small PR to clarify the protocol implementation in the integration tests.
=> Move Tailscale old versions to TS2019 list

.github/workflows/release.yml
Moves to using the `suffix` option in `flavor` from [metadata-action](https://github.com/docker/metadata-action) to ensure  the suffix is applied to all tags. Without this the Alpine image was ending up with the `<version>` tag instead of the Debian image.
Also removed the `type=raw,value=latest` and equivalent options from all three images, as the default behavior of `latest=auto` in `flavor` should take care of this. The `onlatest=true` in the `suffix` option will ensure the Debug and Alpine images will be `latest-debug` and `latest-alpine` respectively.
=> Releases: use flavor to set the tag suffix

CHANGELOG.md, oidc.go, protocol_common.go
We were sending the stripped nodekey on the AuthURL when using OIDC on nodekey expired. 
This PR fixes it.
=> Fix AuthURL on machine expiration when using OIDC

CHANGELOG.md, config-example.yaml, config.go, dns.go
This adds support for easily using [NextDNS](https://nextdns.io/) as a DoH resolver in tailscale network controlled by Headscale. More info in #939 
To enable you would put the following in config:
```yaml
dns_config:
nameservers:
- nextdns:abcdef # Where abcdef is your NextDNS ID
```
Fixes #939
=> Add support for NextDNS resolver

config.go
If users are following https://github.com/juanfont/headscale/blob/main/docs/remote-cli.md, headscale CLI fails to connect to the remove server because no config file is set up (i.e., the remote CLI is fully configured via env vars).
This PR allows headscale running in CLI mode to be run only with env vars.
=> Fix remote CLI when there is no config file present

integration/auth_web_flow_test.go
This minor PR runs the WaitForReady outside the up goroutine, to fix intermittent issues when running the integration tests.
=> WaitForReady in web auth flow integration tests outside up goroutine

app.go, app_test.go, config-example.yaml, config.go, docs/tls.md, integration/hsic/hsic.go, integration_test/etc/alt-config.dump.gold.yaml, integration_test/etc/alt-env-config.dump.gold.yaml, integration_test/etc/config.dump.gold.yaml, integration_test/etc_oidc/base_config.yaml
mTLS was added in one of our first PRs, and it has never been used - as Tailscale clients do not support it.
This PR just removes all the code and references.
=> Remove mTLS code

Makefile
=> Increase integration tests timeout to 120m

docs/running-headscale-container.md
Added the db_type in the sample config.yaml  Without this entry, the container throws Unsupported DB error
`db_type: sqlite3`
=> Correction in the sample config file

docs/proposals/002-better-routing.md
This PR includes a proposal to improve how we handle the routing and subnet routers.
=> Proposal: Better routing management

CHANGELOG.md, app.go, config-example.yaml, config.go
#925 
Change `DBssl` to `String` while still compatible with old boolean configuration.
=> Make more sslmode available for postgresql connection (Fixes #925)

CHANGELOG.md, Dockerfile.tailscale, Dockerfile.tailscale-HEAD, acls.go, acls_test.go, acls_types.go, api_common.go, app.go, integration/cli_test.go, integration/general_test.go, integration/hsic/hsic.go, integration/scenario.go, integration/scenario_test.go, integration/ssh_test.go, integration/tailscale.go, integration/tsic/tsic.go, machine.go
Based on the fork of @db48x from #661. Doesn’t support the ‘autogroup’ ACL functionality.
This ACL works for us (formatted slightly for readability)
```json
{
"acls":[{
"action":"accept",
"src":["group:employees"],
"dst":["tag:proxy:*"]
}
],
"hosts":{},
"groups":{
"group:employees":[
"john.doe",
"jane.doe"
],
"group:proxy":[
"mycorp"
]
},
"tagOwners":{
"tag:proxy":[
"group:proxy"
]
},
"ssh":[
{
"action":"check",
"src":["group:employees"],
"dst":["tag:proxy"],
"users":["some-allowlisted-user"],
"checkPeriod":"8h"
}
],
"disableIPv4":false,
"randomizeClientPort":false
}
```
=> Add SSH ACL support

acls.go, acls_test.go
In preparation for our ACL improvement spree, let's take generateACLRules() out of Headscale.
=> Make core ACL generation function not a Headscale method 

CHANGELOG.md, config-example.yaml, config.go, oidc.go
Added an additional OIDC configuration option for a 'groups' claim. The allowed_groups config option is another OIDC authorization option. I tested this with Keycloak by adding a group membership client scope to the OIDC provider.
=> Added an OIDC AllowGroups option for authorization.

integration/scenario.go
Tailscale 1.16.2 has started failing when fetching from apt, so disable it.
=> Disable Tailscale 1.16 in integration tests

machine.go
When a machine has logged out, it would still show online for the next keepAlivePeriod. 
With this small PR that is solved.
=> Show clients offline when expired

machine.go, routes.go
When using Tailscale v1.34.1, enabling or disabling a route does not effectively add or remove the route from the node's routing table. We must restart tailscale on the node to have a netmap update.
Fix this by refreshing last state change so that a netmap diff is sent.
Also do not include secondary routes in allowedIPs, otherwise secondary routes might be used by nodes instead of the primary route.
Fixes #1075
=> fix(routes): ensure routes are correctly propagated

CHANGELOG.md, app.go, cmd/headscale/cli/nodes.go, integration/auth_web_flow_test.go, integration/tailscale.go, integration/tsic/tsic.go, machine.go, machine_test.go, noise.go, protocol_common.go, protocol_common_utils.go, protocol_legacy.go, protocol_noise.go, protocol_noise_poll.go
Under certain conditions we could get duplicated nodes (e.g., after logout/login, reported in #1054) - due to a misunderstanding from my side on the role of MachineKey in TS2021.
`MachineKey` in TS2021 (the permanent-ish key associated to a client) is no longer sent in the body of the protocol requests, but obtained from the method `Peer()` in the `controlbase.Conn` struct. I was not aware of this (cheers @awsong for the heads up!). Our TS2021 was completely dropping `MachineKey`
Fixes #1054
=> Fix duplicate nodes due to incorrect implementation of the protocol

integration/auth_web_flow_test.go, integration/tailscale.go, integration/tsic/tsic.go
Add a helper method to logout a tailscale client in integration tests.
=> Add logout method to Tailscale interface

protocol_common_poll.go
Prometheus goroutine count:
After some debugging, I found the goroutine leak at `keepAliveChan`, if client is disconnected, server goroutine may block at write  `keepAliveChan`, with a select and check context fix this issue.
https://github.com/juanfont/headscale/blob/3e9ee816f9394f2f40bede40797695cf02ac064e/protocol_common_poll.go#L667
```
goroutine profile: total 153
86 @ 0x43cab6 0x405ecc 0x405a7d 0xfe26ee 0x46dda1
#	0xfe26ed	github.com/juanfont/headscale.(*Headscale).scheduledPollWorker+0x56d	github.com/juanfont/headscale/protocol_common_poll.go:667
```
=> fix goroutine leak

config.go
With this change, domains are applied if there are any `dnsConfig.Resolvers` rather than any `dnsConfig.Nameservers`. Without this change, using nextdns doh would disallow setting any domains (because it checked `dnsConfig.Nameservers` which would be empty in the case of NextDNS DOH).
=> domains/restricted_nameservers: check dnsConfig.Resolvers instead

CHANGELOG.md, config-example.yaml, config.go, docs/README.md, docs/dns-records.md
This PR adds the code of https://github.com/madjam002/headscale/commit/b9f05fca8d7fcc246b44a0495587b9de1582049c but patched into the correct file as the code location now has been updated.
I have run the latest headscale for the last month with this change and it works great! 🥳
My usecase is serving some internal applications such as `grafana.vpn.my.domain` and a have reverse proxy on the host that correctly maps the requests 👍🏻 
I would be willing to add documentation, tests and more if needed, just let me know what you think of merging this before I invest the work ^^  
related to https://github.com/juanfont/headscale/issues/762
Also notifying @madjam002 since the code was originally from him 😊
=> add the possibility for custom DNS records

integration/scenario.go
This PR removes Tailscale v1.18.2 from the test matrix, as it seems to fail downloading from the apt package repository.
=> Remove Tailscale v1.18.2 from test matrix

machine.go, utils.go
…allocate memory
This pr modifies the comparison behavior of the `containsAddresses` function so that Golang does not continuously allocate memory and cause high cpu usage.
=> Fix excessive cpu usage

CHANGELOG.md, app.go, integration/control.go, integration/general_test.go, integration/hsic/hsic.go, integration/scenario.go, integration/scenario_test.go, machine.go, protocol_common.go
This PR implements #1087, to better adhere to a change on how ephemeral nodes behave on logout in the SaaS https://tailscale.com/blog/ephemeral-logout/.
=> Remove ephemeral on logout

integration/hsic/config.go, integration/hsic/hsic.go
This commit sets the Headscale config from env instead of file for integration tests, the main point is to make sure that when we add per test config, it properly replaces the config key and not append it or something similar.
=> Read integration test config from Env

app.go
See https://github.com/juanfont/headscale/issues/1114#issuecomment-1373698441 (probably caused by race conditioning)
=> Fix SIGSEGV crash related to map of state changes

machine.go
…e cpu usage
I've been watching the cpu situation for the past few days, and I found that the cpu occasionally suddenly rises to 500%, so I used pprof to check and found that ToStringSlice causes the cpu to rise.
After optimizing it, the cpu is still rising occasionally, but not very much.
The final solution should be to use the cache to store the machine information for comparison, and modify the database data and cache information only when there are changes. I'm not familiar with it, so I haven't made the appropriate changes yet.
https://user-images.githubusercontent.com/23068780/210695313-54af7475-d527-4274-b33a-50838c44ed98.svg
https://user-images.githubusercontent.com/23068780/210695393-754f2a55-6894-42ac-8ecc-6294109e2f19.svg
=> Repeat ToStringSlice

cmd/headscale/cli/nodes.go, machine.go, oidc.go
Whenever a machine should be refreshed, the new OIDC expiry time wouldn't be persisted. This PR adresses this critical bug. I've also expanded the `nodes list` command to show the expiration time.
=> Refresh machines with correct new expiry

Makefile
test_integration_oidc was removed in 0525bea59310a8e3e8e7d9feebcbd909f482cc92
This change will make `make test_integration` work again.
=> Makefile: remove a missing target

CHANGELOG.md, db.go
The calls to AutoMigrate to other classes that refer to users will
create the table and it will break, it needs to be done before
everything else.
=> Migrate DB: rename table is plural

docs/dns-records.md
This changes the link to a permalink as the relative link was broker after the first addition to the referenced file.
=> permalink in the limitations section to tailscale

machine.go
The previous gorm statement `h.db.Preload("AuthKey").Preload("AuthKey.User").Preload("User").Find(&machines).Where("given_name = ?", givenName)` will get all machines since `Where` after `Find` will be ignored
=> gorm: put Where before Find

docs/reverse-proxy.md
This PR adds documentation on using Apache as a reverse proxy with Headscale.
Related #1160
=> Add hint for reverse proxying with Apache

integration/scenario.go
This PR adds the newly released Tailscale v1.36  to our integration tests.
=> Target Tailscale 1.36.0

db.go
Fixes #1166
This will probably not work for people who has already upgraded to the beta-1.
Users who are using beta-1 should either:
- delete the _empty_ `user_id` column in `machines` and `pre_auth_keys` (make sure its empty...) and rerun with beta-2
- rename the column manually from `namespace_id` to `user_id`
- use beta-2 from their database backup of 0.18.x
=> Migrate namespace_id to user_id column in machine and pak

flake.nix, go.mod, protocol_common_utils.go
This PR tweaks the zstd encoding by using smallzstd package from tailscale and a sync pool, instead of creating a new encoder.
While this won't fix #1014 entirely, it could reduce CPU usage when sending mapresponses to the clients
=> use smallzstd and sync pool

machine.go, routes.go, routes_test.go
As indicated by @bradfitz (thanks!!) at https://github.com/juanfont/headscale/issues/804#issuecomment-1399314002, both routes (IPv4 and IPv6) need to enabled for an exit node to be considered.
This PR makes sure that when enabling 0.0.0.0/0 or ::/0 the other gets enabled too.
=> Enable both exit routes at the same time

CHANGELOG.md, cmd/headscale/cli/routes.go
Currently exit routes are shown as 'False' in the primary column of the CLI - which is not relevant for exit nodes.
This PR fixes that.
Also, adds a missing entry in the changelog.
=> Do not show IsPrimary field as false in exit nodes

CHANGELOG.md, config.go
Fixes #1161 
Tailscale allows split DNS configuration without requiring global nameservers.
In addition, as per [the docs](https://tailscale.com/kb/1054/dns/#using-dns-settings-in-the-admin-console):
> These nameservers also configure search domains for your devices
~In addition, as stated in [the FAQ](https://tailscale.com/kb/1054/dns/#faq):~
> ~Previous versions of the DNS settings page allowed defining search domains separately from nameservers. However, due to cross-platform compatibility reasons, this is no longer possible. To define a search domain, you’ll need to add at least one nameserver along with it.~
This commit aligns headscale to tailscale by:
* ~removing support for `dns_config.domains`~
* honouring `dns_config.restricted_nameservers` regardless of whether any global …
=> Align behaviour of dns_config.restricted_nameservers to tailscale

.github/workflows/test-integration-v2-TestOIDCExpireNodesBasedOnTokenExpiry.yaml, CHANGELOG.md, cmd/gh-action-integration-generator/main.go, config-example.yaml, config.go, integration/auth_oidc_test.go, integration_test/etc/alt-config.dump.gold.yaml, integration_test/etc/alt-env-config.dump.gold.yaml, integration_test/etc/config.dump.gold.yaml, oidc.go
This commit adds a default OpenID Connect expiry to `180d` to align with Tailscale SaaS (previously infinite or based on token expiry).
In addition, it adds an option use the expiry time from the Token sent by the OpenID provider. This will typically cause really short expiry and you should only turn on this option if you know what you are desiring.
This fixes #1176.
=> Set OpenID Connect Expiry

templates/apple.html, templates/windows.html
I added a bit of css to make the configuration guides look better, as they were very rough.
=> Add css to the /windows and /apple templates

docs/running-headscale-openbsd.md
- OpenBSD 7.2 installs go 1.19 by default
- Doubt you can run nix on OpenBSD so skip the makefile/nix build and just go build directly
(this is only an auxiliary docs change so none of the checklist seems relevant)
=> Fix OpenBSD build docs

CHANGELOG.md, cmd/headscale/cli/configtest.go
This adds a "configtest" command-line argument that sets up an instance of Headscale and exits, causing the configuration file and ACLs to be processed.
This solves a problem I've been having where the only way I know to test the ACLs syntax is to restart headscale, and if it fails to start I need to login via another system and correct the problem, then restart headscale.
This is the first time I've touched go, so if you ask too much of me in review I'm likely to be out of my element quickly.  :-)
Fixes #1229
=> Add "configtest" CLI command.

app.go
This commit makes headscale return
HTTP status code 404 (not found) for any
requests it doesn't know how to handle.
=> Return 404 on unmatched routes

CHANGELOG.md, templates/apple.html
updates #205, #296, #515, #58, #659
=> Add instructions on how to login to iOS

docs/exit-node.md
Currently the only kind-of documentation is #210 which is outdated. To remedy this, add a document describing the process.
=> document running exit nodes

protocol_common.go
This PR does 2 things:
- replace time.NewTicker with time.After, because if you use time.Ticker and never stop it, it will leak some resource
- adding the same hacky logic on re-registration of expired machine, without it, the headsacle will got hammered by tailscale client
=> adding some sleep on re-registration after machine expired

.github/workflows/test-integration-v2-TestACLAllowStarDst.yaml, .github/workflows/test-integration-v2-TestACLAllowUserDst.yaml, .github/workflows/test-integration-v2-TestACLDenyAllPort80.yaml, CHANGELOG.md, acls.go, integration/acl_test.go, machine.go, machine_test.go
This should fix #699.
We seemed to have a an implementation where star connections where
filtered out of the netmap preventing a connection to be established.
This should fix this issue.
=> Fix issue where ACL * would filter out returning connections

acls.go, acls_test.go
The existing code in expandACLPeerAddr would generate an incorrect range when using CIDR notation, both for IPv4 and IPv6 - missing the last IPs.
This PR fixes it.
=> Fix CIDR calculation in expandACLPeerAddr

integration/scenario.go
In the last PR I only added the new version in the legacy tests. This PR corrects it.
=> Added 1.38.4 in the new tests

integration/auth_oidc_test.go, integration/auth_web_flow_test.go, integration/scenario.go, integration/tsic/tsic.go
This PR adds an extra check before leaving the Up() helpers, to better detect when a TS version is broken.
=> Make sure all clients of a user are ready

.github/workflows/test-integration-v2-TestACLDevice1CanAccessDevice2.yaml, .github/workflows/test-integration-v2-TestACLNamedHostsCanReach.yaml, .github/workflows/test-integration-v2-TestACLNamedHostsCanReachBySubnet.yaml, Makefile, acls.go, acls_test.go, integration/acl_test.go, integration/utils.go, machine.go
This PR fixes a series of issues with ACLs and IPv6, were it could not be added at all, and then the underlying connection issues that was then exposed.
Updates #809
=> Fix IPv6 in ACLs

.goreleaser.yml, CHANGELOG.md, docs/packaging/postinstall.sh, docs/running-headscale-linux-manual.md, docs/running-headscale-linux.md
This PR replaces the installation instructions for Headscale with new `.deb` based docs, which should make the whole systemd stuff easier on our users.
It also disables rpm for now as per discussion in #1297.
=> Packaging and doc fixups

acls.go, app.go, machine.go
Hi,
this is a possible optimization for the problem in issue #1372.
Not the most elegant solution but it should work.
=> optimize generateACLPeerCacheMap

CHANGELOG.md, noise.go, protocol_noise.go, protocol_noise_poll.go
This PR improves some stuff around our Noise implementation, while adding support for future protocol improvements.
=> Improvements on Noise implementation

Dockerfile.tailscale, Dockerfile.tailscale-HEAD, cmd/build-docker-img/main.go, integration/scenario.go, integration/tsic/tsic.go
=> trim dockerfiles, script to rebuild test images

CHANGELOG.md, docs/running-headscale-linux.md
Fixes empty hyperlink to Headscale's releases page in the installation guide.
=> Add missing GH releases page link

docs/exit-node.md
I propose to add the information, that IP forwarding needs to be enabled in order to use a node as an exit-node.
I omitted the unit tests, integration tests and changelog update, as the change to the documentation should not affect the code.
=> Add IP forwarding requirement to documentation

CHANGELOG.md, routes.go, routes_test.go
We should disable (or delete) both exit routes of a node at the same time - the same way we already enable both.
As per https://github.com/juanfont/headscale/issues/804#issuecomment-1399314002
Fixes #1284
=> Disable and Delete route must affect both exit routes (IPv4 and IPv6)

config-example.yaml
Use clearer language on the example config file for the ip_prefixes value.
=> Add further clarification on unsupported ranges in config example

config-example.yaml, config.go
Reverts juanfont/headscale#1414
=> Revert and fix Unix socket location

CHANGELOG.md, Dockerfile, Dockerfile.debug, config.go
This PR ditches distroless for Docker, and creates the /var/run/headscale path so user do not have issues when using the default config.
=> Docker image improvements

Dockerfile
Add ca-certificates package to fix headscale not being able to resolve OIDC providers correctly due to LetsEncrypt not being in the default certificate registry.
If possible, would be nice to also push this to v0.22.2 so a new version isn't required to be able to use headscale correctly without building your own image.
Fixes #1462
=> Add ca-certificates

cmd/headscale/headscale.go
We were sending the logs to stdout, rather that what seems to be the industry practice of stderr.
https://github.com/rs/zerolog#pretty-logging (our log library seems to prefer stderr)
https://www.reddit.com/r/golang/comments/jqvaft/why_does_the_log_package_always_output_to_stderr/ (go standard log sends to stderr)
But you can find other opinions, of course https://12factor.net/logs
Fixes https://github.com/juanfont/headscale/issues/1519
=> Send logs to stderr, rather than stdout

.github/workflows/stale.yml
We have a lot of issues that has gone stale, and to help us prioritise which ones to pick up, we are adding this stale action to close out issues that are no longer active.
The bot is configured as this:
- If an issue sees no activity for 6 months (180 days) it is marked as stale
- If an issue is not confirmed still being an issue within 14 days, it is closed.
This is of course not a perfect solution, but it will hopefully help us prioritise active issues with people who can help us debug.
We might tighten the activity requirement in the future.
=> Add github stale action

docs/running-headscale-container.md
This should just be simple update to fix this link in the [containers docs](https://headscale.net/running-headscale-container/#configure-and-run-headscale) for the example config, as right now it shows up as:
> Download a copy of the [example configuration][config-example.yaml](https://github.com/juanfont/headscale/blob/main/config-example.yaml) from the headscale repository.
This should fix to look like this:
> Download a copy of the [example configuration](https://github.com/juanfont/headscale/blob/main/config-example.yaml) from the headscale repository.
=> Docs: Update running-headscale-container.md - fix link to example config

.github/workflows/docs.yml, docs/requirements.txt, mkdocs.yml
Latest mkdocs-material fails documentation building about unsupported extenstion. Updated extension and pinned Python packages in `docs/requirements.txt` to major versions to prevent uncontrolled breaking changes in future.
=> Fix Github Actions docs pipeline

flake.nix, go.mod, go.sum, integration/scenario.go
There were important [bugfixes](https://github.com/puzpuzpuz/xsync/pull/111) in v3.0.2, so it's worth upgrading.
=> Update xsync to v3.0.2

CHANGELOG.md, flake.nix, go.mod, go.sum, hscontrol/db/db.go, hscontrol/types/node.go
Up until this commit, headscale has had one massive migration func that runs every time the server starts. This means that every time we have migrated anything, we have added stuff to it and not really taken into account how the database of clients look like. This means that sometimes the new stuff has had to be added in the middle, as it would break things further down.
It is kind of a miracle that it has worked so far with no permament damage, particularly considering some of our larger migrations like Machine -> Node or Namespace -> User.
This commit addresses this by adding gormigrate, which is a simple versioned migration system. As we have to maintain our messy past, the first migration is the large, currently working, but hard to change function. Subsequent changes should be added …
=> add versioned migrations

CHANGELOG.md, hscontrol/db/node.go, hscontrol/mapper/mapper.go, hscontrol/notifier/notifier.go, hscontrol/poll.go, hscontrol/poll_noise.go, hscontrol/types/common.go, integration/general_test.go, integration/run.sh, integration/scenario.go, integration/scenario_test.go
Currently we support informing nodes upon change, but do not have a mechanism for updating the node from control and down.
This commits add a SelfUpdate state change and it is used to inform a node if it keys has been expired control side.
This PR makes 1.36 the last supported version as it exposes keyexpiry information.
fixes #1645
=> implement selfupdate and pass expiry

.github/workflows/test-integration-v2-TestSubnetRouteACL.yaml, hscontrol/db/node.go, hscontrol/mapper/mapper.go, hscontrol/policy/acls.go, hscontrol/policy/acls_test.go, hscontrol/poll.go, integration/route_test.go, integration/tailscale.go, integration/tsic/tsic.go
=> node selfupdate and fix subnet router when ACL is enabled

hscontrol/types/config.go
Reading client secret from file will include a line break, which results in a mismatching client secret compared to reading directly from the config. This ensures that the string is trimmed before building the config.
Fixes #1696.
=> Trim client secret after reading from file

hscontrol/db/routes.go, hscontrol/db/routes_test.go
Fixes #1706 by checking routes enabled state. This PR updates the existing tests and adds an additional test covering the bug. All existing tests were assuming routes to be enabled.
=> Fix failover to disabled route #1706

hscontrol/auth.go
Fixes https://github.com/juanfont/headscale/issues/1675
Fixes https://github.com/juanfont/headscale/issues/1705
These issues started in the v0.23.0 alpha. 
When reauthenticating using oidc, no OldNodeKey is set by the client, the NodeKey set by the client is different from the one headscale has set, but the NodeKey does not get updated to the new one.
A better fix might be to update the nodekey in the RegisterOIDC stack, but my attempts there did not work.
=> Login with OIDC after having been logged out

.github/workflows/test-integration-v2-TestPingAllByIPPublicDERP.yaml, hscontrol/poll.go, hscontrol/types/node_test.go, hscontrol/util/test.go, integration/auth_oidc_test.go, integration/auth_web_flow_test.go, integration/embedded_derp_test.go, integration/general_test.go, integration/tailscale.go, integration/tsic/tsic.go, integration/utils.go
This PR adds three new integration test assert methods which will do the following for the "general" case:
`assertValidNetmap`: in clients which support `tailscale debug netmap` it will dump the netmap and verify that it is in a known "good" state, this includes checking for endpoints, derp relays, ips, online status and more.
`assertValidStatus`: check the output of the `tailscale status` command, checking derp relay, hostname, os, peer ips, network map status and magic sock status
`assertValidNetcheck`: checks that the client has a valid DERP server using output from `tailscale netcheck`.
The "general" case is any all to all communication, it does not account for things like nodes with ACLs and similar.
This also splits "PingAllByAll" into two, one version which use internal DERP for …
=> Add assert func for verifying status, netmap and netcheck

docs/windows-client.md
Add Windows registry command to create the `Tailscale IPN` path before setting properties.
=> docs(windows-client): add Windows registry command

hscontrol/auth.go, hscontrol/grpcv1.go, hscontrol/poll.go
This tries to solve a timing issue where nodes might send updates between the first full map and the channel for getting updates being opened which means they might not get endpoints or derp updates from peers.
In addition, it removes the notifier in the registration stages, with the reasoning that its better to announce when the nodes contacts the poller as it is "more ready" and not missing things like hostinfo.
=> Prepare notify channel before sending first update

docs/tls.md
Move "Bring your own certificates" to the top
since the letsencrypt section is now much longer, it seems wrong to
keep such a short section way down at the bottom.
Restructure "Challenge types" into separate sections
Add technical description of letsencrypt renewals
this aims to answer:
- what can be expected in terms of renewals
- what logs can be expected (none)
- how to validate that renewal happened successfully
- the reason for some of the 'acme/autocert' logs, or at least some best-effort assumptions
=> TLS documentation updates

.goreleaser.yml
This pr fixes the push to dockerhub, it uses `bare` in ko which does not push a massive md5 as part of the container name.
=> fix ko dockerhub builds

hscontrol/tailsql.go
>Headscale is open to code contributions for bug fixes without discussion.
An error value in the `hscontrol` package is unused:
```go
// hscontrol/tailsql.go
certDomains := tsNode.CertDomains()
if len(certDomains) == 0 {
fmt.Errorf("no cert domains available for HTTPS")
}
base := "https://" + certDomains[0]
```
I spotted it with `go vet`:
```text
$ go vet ./...
hscontrol/tailsql.go:73:14: result of fmt.Errorf call not used
```
This PR adds the missing return statement.
=> Use result of fmt.Errorf call

.goreleaser.yml, CHANGELOG.md
This commit tries to align the new docker tags with the old schema
A prerelease will end up with the following tags:
- unstable
- v0.23.0-alpha3
- 0.23.0-alpha3
- sha-1234adsfg
A release will end up with:
- latest
- stable
- v0.23.0
- v0.23
- v0
- 0.23.0
- 0.23
- 0
- sha-1234adsfg
All of the builds will also have a `-debug` version.
I think this addresses the feedback from discord and https://github.com/juanfont/headscale/issues/1561#issuecomment-1946243866.
=> rework docker tags

flake.nix, go.mod, go.sum
gorm broke postgresql upstream.
Fixes https://github.com/juanfont/headscale/issues/1755
=> rollback gorm, broke migration #1755

CHANGELOG.md, docs/running-headscale-container.md, hscontrol/app.go, hscontrol/db/db.go, hscontrol/util/file.go
The new docker image does not have all headscale directories pre-created, and while 99% of the cases, these dirs should be mounted into the container and therefore created, it might be a source of confusion.
This commit improves the error messages for these cases.
Depends on a changelog update after https://github.com/juanfont/headscale/pull/1763
=> improve errors for missing directories

.github/workflows/lint.yml
The versions have been left to rot and they start failing in random ways when we upgrade for example Go.
=> replace linter actions with nix to ensure consistent version

hscontrol/poll.go, hscontrol/util/util.go, hscontrol/util/util_test.go, integration/embedded_derp_test.go, integration/tsic/tsic.go, integration/utils.go
This version uses `tailscale debug watch-ipn` as
it is available in all supported versions, and it
does not seem to have any weird side effect when using
Patch updates (empty values).
=> Get integration test netmap from watch-ipn command

hscontrol/db/db.go
sqlite ignores if it doesnt exits, postgres errors.
=> fix postgres migration

cmd/headscale/cli/preauthkeys.go, hscontrol/db/preauth_keys.go, hscontrol/db/preauth_keys_test.go
In Tailscale SaaS, ephemeral keys can be single-user or reusable. Until now, our ephemerals were only reusable. 
This PR makes us adhere to the .com behaviour. Fixes the issue reported in #1712.
=> Ephemeral keys can now be reusable and non-reusable

.github/workflows/build.yml, .github/workflows/check-tests.yaml, .github/workflows/contributors.yml, .github/workflows/docs.yml, .github/workflows/gh-actions-updater.yaml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/test-integration.yaml, .github/workflows/test.yml, .github/workflows/update-flake.yml
What is changed by this PR:
- Updates the various actions used for the projects workflows
- Changes the `tj-actions/changed-files` to better maintained action `dorny/paths-filter` usage is basically the same and from what i tested its working as expected.
- This also allows a better granularity for the file filters with more options to conditionally run what is needed. 
```yaml
- name: Get changed files
id: changed-files
uses: dorny/paths-filter@v3
with:
filters: |
yaml-files:
- 'config-example.yaml'
go-files
- '**/*.go'
nix-files
- '*.nix'
```
and the you can use it with `steps.changed-files.outputs.<filter-name> == 'true'` to run it only if the files from that filter were changed.
- Small adjustments to file formatting
As next step i would like to introduce some naming conventions for …
=> update gh workflow actions

hscontrol/poll.go
This seems to be logged once every 15 to 20 seconds for each machine and belonging to background activities, so it should belong to debug logging level or even trace
=> Downgrade update sent to debug

integration/embedded_derp_test.go, integration/general_test.go, integration/hsic/hsic.go
QoL and Dry improvement. 
Over time I want to try to use this option more to see if I can make the integration tests able to run offline, would be nice when working on flight.
But I'm sure docker and other things that always wants to fetch things will put a stopper to that anyways...
=> move "embedded derp" settings into With options for integration tests

cmd/headscale/headscale.go, flake.nix, go.mod, go.sum
jagottsicher's fork fixed a bug in Windows implementation. While Windows may be not intended as a target platform, some contributors (yours truly included) may prefer it for development.
Also ran go mod tidy, thus three more unnecessary lines are removed from go.sum
Fixes #1842
=> Use newer fork of termcolor

CHANGELOG.md, cmd/headscale/cli/root.go
This will result in the message being logged to stderr. Logging this to stdout may break some scripts that use the output of headscale commands.
=> Log available update as warning

hscontrol/db/db.go
This PR fixes a crash reported in Discord https://gist.github.com/christian-heusel/d4eb0fbe529348a86b4cfc76d516ef23.
When a family is not being used (e.g., a user did not have configured IPv6 in their prefixes) the migration would crash, as it was accessing an empty ptr.
=> Fix crash when a prefix family was empty

config-example.yaml, hscontrol/types/config.go, integration/hsic/config.go
This PR removes a now unused config parameter.
The param has been deprecated since the rework of the mapper.
=> Remove unused node check interval

hscontrol/db/node.go, hscontrol/db/node_test.go
This PR fixes #1849, by allowing to set an empty list of tags from CLI or API.
=> Allow to remove forced tags of a node

integration/scenario.go
=> chore: fix function names in comment

hscontrol/app.go, hscontrol/auth.go, hscontrol/auth_noise.go, hscontrol/db/node.go, hscontrol/db/node_test.go, hscontrol/db/preauth_keys_test.go, hscontrol/db/routes.go, hscontrol/db/routes_test.go, hscontrol/grpcv1.go, hscontrol/mapper/mapper.go, hscontrol/metrics.go, hscontrol/noise.go, hscontrol/notifier/metrics.go, hscontrol/notifier/notifier.go, hscontrol/oidc.go, hscontrol/poll.go, hscontrol/types/node.go, integration/acl_test.go, integration/auth_oidc_test.go, integration/auth_web_flow_test.go, integration/cli_test.go, integration/embedded_derp_test.go, integration/general_test.go, integration/hsic/hsic.go, integration/route_test.go, integration/scenario.go, integration/scenario_test.go, integration/ssh_test.go
- adds WithTuning parameters to hsic and makes retry max wait into an argument for scenario
- fix some logs that should be trace that was info
- redo/add metrics for the new update model
- reduce how long notifier hold locks (per node instead of all nodes)
- use concurrency safe map for online status (could trigger racy panic), fixes #1862
=> metrics, tuning in tests, db cleanups, fix concurrency issue

README.md
This PR expands a bit the relation with Tailscale in our `README.md`.
Basically, Kristoffer is a part of the Tailscale technical staff and he is allowed to spend work hours working in headscale.
Only us the maintainers set the direction of the project. Our only obsession is to have a sustainable project that does not get us burned out.
=> Clarify relation with Tailscale

Dockerfile.debug
Makes sure everything is installed first, then build go stuff.
Main purpose is to make us able to rebuild the container offline since we mostly have the first apt layers cached, but since we did go first, it would always invalidate.
=> remove multistep build, build go last, allowing cached build layers (for debug image)

hscontrol/noise.go
This PR fixes #1883 
Basically do not access in node if we failed to find it.
=> Do not access node ID when node is not found

hscontrol/app.go, hscontrol/notifier/metrics.go, hscontrol/notifier/notifier.go, hscontrol/notifier/notifier_test.go, hscontrol/poll.go, hscontrol/types/common.go, integration/hsic/hsic.go, integration/route_test.go
This PR will move the batching and deduplication of node updates into the notifier, instead of the poller.
This saves a huge amount of traffic going between and removes quite a lot of unnecessary updates when nodes are connecting and informing us several times.
=> batch updates in notifier

.github/pull_request_template.md, CONTRIBUTING.md, README.md
This PR adds a `CONTRIBUTING.md` document, detailing headscale's contribution policy.
The document is open for discussion with the community, and we welcome suggestions and adjustments.
Our objective is to have a sustainable project that serves the community, and does not burn out its maintainer.
=> Add contributing document

CHANGELOG.md, hscontrol/policy/acls.go, hscontrol/policy/acls_test.go
This PR contains two features: 
- `autogroup:internet` for policy
- fix of a too aggressive reduction of node specific rules
The majority of lines in this PR is tests based on #1817 and #1786.
Fixes #1817
Fixes #1786
Updates #657
=> add autogroup:internet, fix reduce filter rules

hscontrol/types/node.go
=> fix issue preveting get node when disco is missing

.github/workflows/test-integration.yaml, hscontrol/auth.go, integration/cli_test.go
=> fix preauth key logging in as previous user

hscontrol/app.go, hscontrol/notifier/notifier.go
=> trace log and notifier shutdown

docs/running-headscale-openbsd.md
OpenBSD packages a reasonably up to date version of headscale now (0.22.1), if that's actually too old then feel free to just close this
7.1/7.2 are no longer supported so remove references to them
=> low priority PR - Update OpenBSD installation docs for 2024

docs/running-headscale-linux.md
---
Made some small changes to the docs to make linux easier to install, notably because "sudo apt install headscale.deb" doesn't seem to be a valid apt command. You have to reference with leading dot to prevent it from seeing as package name.
Also I changed the link to the github `/latest` release since presumably we don't want people who are just getting started installing alpha versions (which appear first in GitHub)
=> [DOCS] Make linux installation instructions more clear

cmd/headscale/cli/root.go, hscontrol/types/config.go
like TRC DNS configuration loaded dns_config={....}
Closes #1576
=> Initialize log config earlier to prevent trace messages being printed early on

Dockerfile.tailscale-HEAD, flake.nix, go.mod, go.sum, hscontrol/app.go, hscontrol/metrics.go, hscontrol/noise.go, hscontrol/notifier/metrics.go, hscontrol/notifier/notifier.go, hscontrol/notifier/notifier_test.go, hscontrol/poll.go, hscontrol/types/config.go, hscontrol/types/node.go, integration/general_test.go, integration/hsic/hsic.go, integration/scenario.go, integration/tailscale.go, integration/tsic/tsic.go
This PR removes the complicated session management introduced in https://github.com/juanfont/headscale/pull/1791 which kept track of the sessions in a map, in addition to the channel already kept track of in the notifier.
Instead of trying to close the mapsession, it will now be replaced by the new one and closed after so all new updates goes to the right place.
The map session serve function is also split into a streaming and a non-streaming version for better readability.
RemoveNode in the notifier will not remove a node if the channel is not matching the one that has been passed (e.g. it has been replaced with a new one).
A new tuning parameter has been added to added to set timeout before the notifier gives up to send an update to a node.
Add a keep alive resetter so we wait with …
=> Simplify map session management

hscontrol/db/db.go
most of the time we dont even check this error and checking the string for particular errors is very flake as different databases (sqlite and psql) use different error messages, and some users might have it in other languages.
Fixes #1956
=> remove last_successful_update error check

CHANGELOG.md, hscontrol/handlers.go
This patch adds a simply styles to the registration screen.
This should be particular helpful on mobile devices since this makes the user interface responsive and means that you don't have to deal with a tiny font size.
This is how this looks like on a mobile device before and after:
I hope it's fine that I didn't open an issue for this first since it's just a small thing.
=> Make registration screen easier to use

docs/android-client.md
The current Tailscale app for Android looks and behaves differently. This patch updates the documentation for that.
=> Fix Android docs

hscontrol/db/node.go, hscontrol/db/routes.go, hscontrol/derp/derp.go, hscontrol/mapper/mapper.go, hscontrol/notifier/notifier_test.go, hscontrol/policy/acls.go, hscontrol/policy/acls_test.go
Remove the allocation of lists before they are used.
=> Remove allocations of lists before use

CHANGELOG.md, config-example.yaml, hscontrol/db/db.go, hscontrol/types/config.go
this commit makes headscale correctly enable write-ahead-log for sqlite and adds an option to turn it on and off.
WAL is enabled by default and should make sqlite perform a lot better, even further eliminating the need to use postgres.
It also adds a couple of other useful defaults.
Note, this PR removes WAL from the sqlite connection string, as that did not have any effect with the sqlite driver we use.
Fixes #1983
=> Make write-ahead-log default and configurable for sqlite

CHANGELOG.md, config-example.yaml, hscontrol/mapper/mapper.go, hscontrol/mapper/mapper_test.go, hscontrol/mapper/tail.go, hscontrol/types/config.go, hscontrol/types/node.go, hscontrol/types/node_test.go
This commit fixes an issue where search domains was ignored
if the user has not configured any external resolvers. Based
on tailscale's documentation, there is no mention of this
behaviour as far as I can see:
https://tailscale.com/kb/1054/dns#search-domains
In addition, it does add the missing base domain to the
search domain.
and
This commit removes the username from magicDNS names.
This is in preparation of fixing tags, which currently is
not correctly disassociated from users when added. With the
current behaviour, fixing tagged devices would break the
MagicDNS behaviour.
This brings headscale to use the same behaviour of tailscale.
Fixes #1963
Updates #1369
=> fix search domains and remove username from magicdns

.golangci.yaml
When running lints, golangci-lint complained about removed linters (which were already disabled).
This removes the relevant warnings.
Would you be interested in follow up PRs to address the existing warnings? (Ultimately enabling golangci-lint in the CI I guess?)
=> Remove deprecated linters from golangci-lint

hscontrol/types/node.go, hscontrol/types/node_test.go
Added a new function `RegisterMethodToV1Enum()` to Node, converting the internal register method string to the corresponding V1 Enum value. Included corresponding unit test in `node_test.go` to ensure correct conversion for various register methods.
=> fix(1996): Implement register method enum converter

cmd/headscale/cli/policy.go, cmd/headscale/cli/utils.go, hscontrol/app.go, hscontrol/auth.go, hscontrol/db/db.go, hscontrol/db/ip.go, hscontrol/db/ip_test.go, hscontrol/db/node_test.go, hscontrol/db/policy.go, hscontrol/db/routes.go, hscontrol/db/routes_test.go, hscontrol/mapper/mapper.go, hscontrol/metrics.go, hscontrol/notifier/notifier.go, hscontrol/oidc.go, hscontrol/policy/acls.go, hscontrol/policy/acls_test.go, hscontrol/policy/acls_types.go, hscontrol/poll.go, hscontrol/types/config.go, integration/cli_test.go, integration/control.go, integration/hsic/hsic.go
This is mostly an automated change with `make lint`.
I had to manually please golangci-lint in routes_test because of a short variable name.
This is best merged after #2018 to make sure golanci-lint does its job.
=> reformat code

config-example.yaml
Very minor fix to some inline documentation in `config-example.yaml`, where YAML was still mentioned in the context of ACL policy files.
https://github.com/juanfont/headscale/pull/1792 removed support for YAML formatted policy files, as also noted in `CHANGELOG.md`: https://github.com/juanfont/headscale/blob/b799245f1e0a09217dd7e5f6730df9530c67458f/CHANGELOG.md#L47-L48
=> config-example.yaml: Remove reference to yaml for policy files

hscontrol/db/node_test.go
- This PR addresses data race issues detected by the `-race` flag during `gotestsum -- -short -coverprofile=coverage.out ./...` execution for the `EphemeralGarbageCollector` tests. 
The changes include:
- Added necessary synchronization with mutex locks to prevent concurrent access issues.
- Ensured that shared data structures are properly protected during test execution.
- gotestsum -- -race -coverprofile=coverage.out ./...
```
=== Failed
=== FAIL: hscontrol/db TestEphemeralGarbageCollectorOrder (6.00s)
==================
WARNING: DATA RACE
Read at 0x00c00057e198 by goroutine 276:
github.com/juanfont/headscale/hscontrol/db.TestEphemeralGarbageCollectorOrder()
/Users/dongjunna/headscale/hscontrol/db/node_test.go:620 +0x414
testing.tRunner() …
```
=> Fix data race issues in EphemeralGarbageCollector tests

hscontrol/grpcv1.go
This PR addresses the issue where the gRPC API fails to resolve relative policy file paths, unlike the server startup behavior. The fix ensures consistent handling of relative paths across server startup, CLI commands, and gRPC API calls.
- Modified the policy file path resolution logic in the gRPC API handler to match the server startup behavior.
- Ensured that relative paths are resolved relative to the location of the config.yaml file.
Fixes #2050
=> Fix command get policy works with relative policy path

config-example.yaml, hscontrol/db/db.go, hscontrol/types/config.go, hscontrol/util/log.go
This PR integrates the GORM logger with zerolog to detect database-related bottlenecks. With this integration, the log level now follows the level set in zerolog (e.g., debug.level), ensuring consistent and detailed logging for database operations.
To activate database debugging, make sure to set `log.level` to `debug` and `database.debug` to `true`.
Additionally, custom configuration options for GORM have been added. Example configurations can be found in config-example.yaml. The available options include:
```
database:
...
debug: false
gorm:
prepare_stmt: true
parameterized_queries: true
skip_err_record_not_found: true
slow_threshold: 1000
```
- SlowThreshold (ms): Sets the duration threshold for logging slow queries.
- ParameterizedQueries (bool): Provides the option to enable query …
=> Integrate GORM Logger with Zerolog and Add Configuration Options for Logging and Performance

.github/workflows/lint.yml
CI was producing this kind of messages:
> [config_reader] The output format `github-actions` is deprecated, please use `colored-line-number`
(see https://github.com/juanfont/headscale/actions/runs/9994119669/job/27623152138#step:6:206)
This also restore golangci-lint action which was not properly linting files due to the extra `.`  passed (we can expect it to fail if there are some non compliant files).
=> actually lint file on CI

CHANGELOG.md, hscontrol/policy/acls.go, hscontrol/policy/acls_test.go
=> Allow nodes to use SSH agent forwarding

CHANGELOG.md, hscontrol/mapper/mapper_test.go, hscontrol/mapper/tail.go, hscontrol/mapper/tail_test.go, hscontrol/metrics.go, hscontrol/noise.go, hscontrol/poll.go, integration/scenario.go
From 0.23.0, headscale has a goal of supporting the 10 latest versions of tailscale, this PR removes versions older than 1.56.
This allows us to remove a bunch of code, some duplicate! 🎉 
=> remove versions older than 1.56

docs/running-headscale-container.md
Some commands such as `nodes delete` require user interaction and they fail if `-it` is no supplied to `docker exec`. Use `docker exec -it` in documentation examples to also make them work in interactive commands.
See: #2147
=> Add -it to docker exec

docs/web-ui.md
Hi! I have developed a UI for Headscale which I have running in production on my server currently.
It is designed for multi-user tailnets, to allow users to manage their nodes entirely on their own, without providing any sysadmin features.
It offers management (rename, delete, logout, exit node, routes) of nodes, and intercepts the /register endpoint (if using a correctly configured reverse proxy), to allow users to add their own nodes.
Users must authenticate through Github OAuth2 and the list of allowed users are predefined up-front by the admin.
=> [docs] Add Ouroboros to community web ui list

hscontrol/db/preauth_keys_test.go, integration/general_test.go
tailscale/tailscale@1eaad7d broke our reauth test as it makes the client retry with https/443 if it reconnects within 2 minutes.
This commit fixes this by running the test as a two part,
- with https, to confirm instant reconnect works
- with http, and a 3 min wait, to check that it work without.
The change is not a general consern as headscale in prod is ran with https.
Updates #2164
=> make reauth test compat with tailscale head

.github/workflows/test-integration.yaml, CHANGELOG.md, hscontrol/poll.go, hscontrol/types/node.go, hscontrol/types/node_test.go, integration/general_test.go
=> #2140 Fixed reflection of hostname change

docs/about/clients.md, docs/usage/connect/apple.md, hscontrol/templates/apple.go
- Documentation
- Updated `docs/about/clients.md`, added `tvOS` as client.
- Updated `docs/usage/connect/apple.md`, added Installation and configuration documentation for tvOS.
- Updated `hscontrol/templates/apple.go` to also display the tvOS configuration at `/apple` on a deployed headscale instance.
=> Feature tvos documentation

.goreleaser.yml, CHANGELOG.md
This fixes my issue #2171
The resulting test containers with working `stable-debug` tag can be checked [here](https://github.com/docgalaxyblock/headscale/pkgs/container/headscale/versions)
My test workflow run was [this one](https://github.com/docgalaxyblock/headscale/actions/runs/11764777603/job/32770312683)
---
=> fix: missing stable-debug tag

docs/ref/integration/tools.md, docs/ref/integration/web-ui.md, docs/setup/install/community.md, mkdocs.yml
As suggested [in the chat](https://discord.com/channels/896711691637780480/896711692120129540/1299825947142389780). Reword and simplify the web-ui page a bit.
=> Add a page for third-party tools

.prettierignore, docs/ref/remote-cli.md
* Document to either use a minimal configuration file or environment
variables to connect with a remote headscale instance.
* Document a workaround specific for headscale 0.23.0.
* Remove reference to ancient headscale version.
* Use `cli.insecure: true` or `HEADSCALE_CLI_INSECURE=1` to skip
certificate verification.
* Style and typo fixes
Ref: #2193
=> Refresh remote CLI documentation

docs/ref/tls.md
The Tailscale Android client fails silently if the full certificate chain is not provided.
=> Update tls.md to mention using the full cert chain

Dockerfile.tailscale-HEAD, integration/embedded_derp_test.go, integration/tsic/tsic.go
=> Websocket derp test fixes

CHANGELOG.md, hscontrol/types/config.go, hscontrol/types/config_test.go, hscontrol/types/testdata/base-domain-in-server-url.yaml
Requirements [here][1]:
> OK:
> server_url: headscale.com, base: clients.headscale.com
> server_url: headscale.com, base: headscale.net
>
> Not OK:
> server_url: server.headscale.com, base: headscale.com
>
> Essentially we have to prevent the possibility where the headscale
> server has a URL which can also be assigned to a node.
>
> So for the Not OK scenario:
>
> if the server is: server.headscale.com, and a node joins with the name
> server, it will be assigned server.headscale.com and that will break
> the connection for nodes which will now try to connect to that node
> instead of the headscale server.
Fixes https://github.com/juanfont/headscale/issues/2210
[1]: https://github.com/juanfont/headscale/issues/2210#issuecomment-2488165187
=> config: loosen up BaseDomain and ServerURL checks

.github/workflows/test-integration.yaml, Dockerfile.derper, hscontrol/app.go, hscontrol/handlers.go, hscontrol/types/node.go, integration/README.md, integration/derp_verify_endpoint_test.go, integration/dsic/dsic.go, integration/embedded_derp_test.go, integration/hsic/hsic.go, integration/integrationutil/util.go, integration/scenario.go, integration/tailscale.go, integration/tsic/tsic.go
Fixes #1953
By implementing `/verify` endpoint, derper can verify whether the client is in the node list of Headscale by specifying the `--verify-client-url` parameter to `/verify` in Headscale.
This is a continued work on PR #1957, which includes integration testing to meet Headscale's merge requirements.
I am willing to participate in updating the related documentation and change logs, if needed. (Of course, I believe @117503445 is also willing)
=> feat: support client verify for derp (add integration tests)

.golangci.yaml, flake.nix, hscontrol/db/db_test.go, hscontrol/db/ip_test.go, hscontrol/db/node_test.go, hscontrol/oidc.go, hscontrol/policy/acls.go, hscontrol/policy/acls_test.go, hscontrol/templates/windows.go, hscontrol/types/config_test.go, hscontrol/util/string_test.go, integration/acl_test.go, integration/cli_test.go, integration/general_test.go, integration/route_test.go, integration/scenario.go
Fixes a good bunch, still some left.
=> more linter fixups

config-example.yaml, hscontrol/db/db.go, hscontrol/types/config.go
SQLite WAL addition disabled auto checkpoint, this makes the WAL grow forever, not sure why I did that.
Make it configurable, set it to SQLite default.
Fixes #2204
=> make configurable wal auto checkpoint

.github/workflows/test-integration.yaml, CHANGELOG.md, cmd/headscale/cli/mockoidc.go, config-example.yaml, flake.nix, go.mod, go.sum, hscontrol/db/db.go, hscontrol/db/db_test.go, hscontrol/db/node.go, hscontrol/db/node_test.go, hscontrol/db/preauth_keys.go, hscontrol/db/preauth_keys_test.go, hscontrol/db/routes.go, hscontrol/db/routes_test.go, hscontrol/db/suite_test.go, hscontrol/db/users.go, hscontrol/db/users_test.go, hscontrol/grpcv1.go, hscontrol/oidc.go, hscontrol/policy/acls.go, hscontrol/types/config.go, hscontrol/types/preauth_key.go, hscontrol/types/users.go, hscontrol/util/dns.go, integration/auth_oidc_test.go, integration/cli_test.go, integration/dockertestutil/execute.go
This commit hardens the migration part of the OIDC from the old username based approach to the new sub based approach and makes it possible for the operator to opt out entirely.
Fixes #1990
=> Harden OIDC migration and make optional

hscontrol/app.go, hscontrol/db/node_test.go, hscontrol/db/routes.go, hscontrol/grpcv1.go, hscontrol/mapper/mapper.go, hscontrol/mapper/mapper_test.go, hscontrol/policy/acls.go, hscontrol/policy/acls_test.go, hscontrol/types/users.go
currently, the policy approach node to user matching with a quite naive approach looking at the username provided in the policy and matched it with the username on the nodes. This worked ok as long as usernames were unique and did not change.
As usernames are no longer guarenteed to be unique in an OIDC environment we cant rely on this.
This changes the mechanism that matches the user string (now user token) with nodes:
- first find all potential users by looking up:
- database ID
- provider ID (OIDC)
- username/email
If more than one user is matching, then the query is rejected, and zero matching nodes are returned.
When a single user is found, the node is matched against the User database ID, which are also present on the actual node.
This means that from this commit, users can use the …
=> Resolve user to stable unique ID in policy

.github/workflows/test-integration.yaml, hscontrol/app.go, hscontrol/auth.go, hscontrol/db/node_test.go, hscontrol/db/routes.go, hscontrol/grpcv1.go, hscontrol/mapper/mapper.go, hscontrol/mapper/mapper_test.go, hscontrol/mapper/tail.go, hscontrol/mapper/tail_test.go, hscontrol/oidc.go, hscontrol/policy/pm.go, hscontrol/policy/pm_test.go, hscontrol/poll.go, integration/cli_test.go, integration/hsic/hsic.go
this PR "wraps" the policy in a manager interface, and implements it for the policy v1. 
This work has two goals,
- A stepping stone to change how often we recreate the policy when used in netmap creations
- An interface that can be implemented by a _new_ policy implementation to make it easier to run both or tests both. Making us able to introduce a new one, while having the old available while we work out bugs and so on.
=> wrap policy in policy manager interface

.prettierignore, README.md, docs/about/faq.md, docs/ref/configuration.md, docs/ref/integration/tools.md
… and fix some broken links and markdown rendering.
Fixes: #2257
---
=> Add FAQ entry on which database to use

.github/workflows/docs-deploy.yml, .github/workflows/gh-actions-updater.yaml, .github/workflows/release.yml, .github/workflows/stale.yml, .github/workflows/update-flake.yml
This is just a simple change. 
This will configure some actions to be skipped for forks, as the actions that are changed here depend on the main repository or the configured secrets, so it makes no sense to run them for forks. This will also remove failed cron jobs from the forks, rest of the actions that don't depend on anything are left untouched.
=> chore: configure some actions to be skipped for forks

CHANGELOG.md, config-example.yaml, hscontrol/types/config.go, hscontrol/types/testdata/base-domain-in-server-url.yaml, hscontrol/types/testdata/base-domain-not-in-server-url.yaml, hscontrol/types/testdata/dns_full.yaml, hscontrol/types/testdata/dns_full_no_magic.yaml
Upgrade the use of `dns.use_username_in_magic_dns` or `dns_config.use_username_in_magic_dns` to a fatal error and remove the option from the example configuration and integration tests.
Fixes: #2219
=> Remove use_username_in_magic_dns option

.github/workflows/docs-deploy.yml, .github/workflows/test-integration.yaml, CHANGELOG.md, Dockerfile.integration, Makefile, flake.nix, go.mod, go.sum, hscontrol/app.go, hscontrol/auth.go, hscontrol/db/db_test.go, hscontrol/dns/extrarecords.go, hscontrol/mapper/mapper.go, hscontrol/mapper/mapper_test.go, hscontrol/mapper/tail_test.go, hscontrol/oidc.go, hscontrol/types/config.go, hscontrol/types/config_test.go, hscontrol/util/dns.go, integration/auth_oidc_test.go, integration/dns_test.go, integration/utils.go
Add worker reading extra_records_path from file.
Fixes #2262
=> Add worker reading extra_records_path from file

hscontrol/app.go, hscontrol/policy/pm.go, hscontrol/types/config.go
=> fix sighup issue with empty acl

hscontrol/types/users.go, hscontrol/types/users_test.go
Jumpcloud send invalid json, so we need to handle it.
Fixes #2293
=> fix issue where some oidc claim bools are sent as string

hscontrol/dns/extrarecords.go, integration/dns_test.go
=> fixes to extra-record file watcher

docs/usage/connect/apple.md, hscontrol/templates/apple.go
=> Correct macOS GUI connect guide because there's no ALT key on a mac

.github/workflows/test-integration.yaml, CHANGELOG.md, config-example.yaml, docs/ref/oidc.md, hscontrol/oidc.go, hscontrol/types/config.go, integration/auth_oidc_test.go
From PR #1812 :
To fix the error "Could not exchange code for the token" when using the PKCE method, a verifier should be generated and used during the authentication process.
This change include change in configuration, oidc handling method and documents.
```yaml
oidc:
pkce:
enabled: false
method: S256
```
=> feat: Add PKCE Verifier for OIDC

docs/usage/connect/apple.md, hscontrol/templates/apple.go
The official iOS app now has a simpler login process for custom instances, directly within the app.
=> Update apple.md for latest version of iOS

hscontrol/mapper/mapper.go, hscontrol/types/config.go
Fixes #2336
Closes #2344
Closes #2318
=> use headscale server url as domain instead of base_domain

CHANGELOG.md, config-example.yaml, hscontrol/types/config.go
set `oidc.map_legacy_users` to false as per deprecation plan from 0.24
=> set oidc.map_legacy_users false

CHANGELOG.md, hscontrol/types/users_test.go, hscontrol/util/dns.go
=> relax user validation to allow emails, add tests from various oidc providers

CHANGELOG.md, hscontrol/policy/acls.go, hscontrol/policy/acls_test.go, hscontrol/types/users.go
simplify findUserByToken in ACL, add missing testcases
Fixes #2377
=> simplify findUserByToken in ACL, add missing testcases

CHANGELOG.md, hscontrol/db/db.go
The routes table has a NOT NULL constraint on node_id.
Fixes: #2376
=> Remove routes without a node_id

CHANGELOG.md, hscontrol/db/db.go, hscontrol/db/preauth_keys_test.go, hscontrol/types/node.go, hscontrol/types/preauth_key.go
we need to be able to look up the tags on the key, never delete, only expire if in use. There is no API for deleting, but never know if people edit the database.
=> do not allow preauth keys to be deleted if assigned to node

CHANGELOG.md, hscontrol/db/users.go, hscontrol/util/dns.go
=> no edit of oidc users, minimum hostname length

CHANGELOG.md, hscontrol/auth.go, hscontrol/auth_test.go, hscontrol/db/preauth_keys.go, hscontrol/db/preauth_keys_test.go, hscontrol/grpcv1.go, hscontrol/handlers.go, hscontrol/noise.go, hscontrol/oidc.go, hscontrol/platform_config.go
This PR continues the work of #2384 by classifying all the web errors and sending appropriate error codes, instead of just 500 for everything.
Depends on #2374 
Fixes #2390
=> Return better web errors to the user

README.md, docs/about/faq.md, docs/about/features.md, docs/index.md, docs/setup/install/community.md, docs/setup/install/container.md, docs/setup/install/official.md, docs/setup/requirements.md, docs/usage/getting-started.md
Separate the term "tailnet" from user and be more explicit about providing a single tailnet.
Also be more explicit about users. Refer to "headscale users" when mentioning commandline invocations and use the term "local users" when discussing unix accounts.
Fixes: #2335
=> Headscale implements a single tailnet

hscontrol/app.go, hscontrol/auth.go, hscontrol/db/node.go, hscontrol/db/routes.go, hscontrol/grpcv1.go, hscontrol/notifier/notifier.go, hscontrol/oidc.go, hscontrol/poll.go, hscontrol/types/common.go
This helps preventing messages being sent with the wrong update type and payload combination, and it is shorter/neater.
=> use helper function for constructing state updates

CHANGELOG.md, flake.nix, go.mod, go.sum, hscontrol/app.go, hscontrol/debug.go
This PR switches the homegrown debug endpoint to using tsweb.Debugger, a neat toolkit with batteries included for pprof and friends, and making it easy to add additional debug info:
I've started out by adding a bunch of "introspect" endpoints
So users can see the acl, filter, config, derpmap and connected nodes as headscale sees them.
=> use tsweb debugger

.goreleaser.yml, CHANGELOG.md, Dockerfile.integration, Dockerfile.tailscale-HEAD, flake.lock, flake.nix, go.mod
=> update to go 1.24

CHANGELOG.md, hscontrol/noise.go, integration/auth_key_test.go
This commit handles register auth errors as the
Tailscale clients expect. It returns the error as
part of a tailcfg.RegisterResponse and not as a
http error.
In addition it fixes a nil pointer panic triggered by not handling the errors as part of this chain.
Fixes #2434
=> handle register auth errors

docs/about/faq.md, docs/about/releases.md, docs/setup/install/container.md
=> Container images are also available on GHCR

.github/ISSUE_TEMPLATE/bug_report.yaml
updates the debug template with stricter language about debug info, warn users that poorly collected information will have your issue closed.
=> update bug template with debug

config-example.yaml, hscontrol/debug.go
Some endpoints in /debug send JSON data as string. Set the Content-Type header to "application/json" which renders nicely in Firefox.
Mention the /debug route in the example configuration.
---
=> Set content-type to JSON for some debug endpoints

.github/workflows/test-integration-policyv2.yaml, .github/workflows/test-integration.yaml, hscontrol/mapper/mapper_test.go, hscontrol/mapper/tail.go, hscontrol/mapper/tail_test.go, hscontrol/routes/primary.go, hscontrol/routes/primary_test.go, hscontrol/types/node.go, hscontrol/util/string.go, hscontrol/util/util.go, hscontrol/util/util_test.go, integration/acl_test.go, integration/auth_key_test.go, integration/auth_oidc_test.go, integration/auth_web_flow_test.go, integration/cli_test.go, integration/control.go, integration/derp_verify_endpoint_test.go, integration/dns_test.go, integration/dsic/dsic.go, integration/embedded_derp_test.go, integration/general_test.go, integration/hsic/hsic.go, integration/route_test.go, integration/scenario.go, integration/scenario_test.go, integration/ssh_test.go, integration/tailscale.go, integration/tsic/tsic.go
Currently the integration tests only support a single network (with the exception of DERP which has a custom implementation).
This is making it hard to properly test subnet routers (and exit nodes), we currently only look at the output map sent to the nodes.
The goal here is to mold the integration tests into something that supports nodes in multiple docker networks so we can test some basic features.
=> Multi network integration tests

.github/workflows/test-integration-policyv2.yaml, .github/workflows/test-integration.yaml, hscontrol/app.go, hscontrol/auth.go, hscontrol/grpcv1.go, hscontrol/policy/v1/policy.go, integration/acl_test.go, integration/control.go, integration/hsic/hsic.go, integration/route_test.go
Depends on #2489
Fixes #2497
Fixes #2485
=> fix auto approver on register and new policy

docs/ref/integration/web-ui.md
This PR adds unraid-headscale-admin to the docs.
unraid-headscale-admin is a simple Plugin for Unraid which adds a simple WebUI for Headscale directly into Unraid which then can communicate in Local Mode (when running the official Headscale Docker container directly on the same machine through `docker exec`) or API Mode (I think the API Mode is self explanatory) with Headscale.
=> Add unraid-headscale-admin web UI to docs

CHANGELOG.md, hscontrol/db/node.go, hscontrol/db/node_test.go, hscontrol/mapper/mapper.go
Querying the whole database becomes a performance issue if a lot of nodes exist in it, even if all those nodes are offline. In `PeerChangedResponse` we actually know which nodes need to be queried, so we can restrict the database queries to these nodes.
In my tests, `PeerChangedResponse` usually needed to query less than 5 nodes, so the change resulted in an order of magnitude better performance for a database with several hundred nodes (most of them offline).
I can also write a test if desired. The PR should not change any behavior, so I wanted to base tests on existing tests for `PeerChangedResponse`. However, I did not find any existing tests for this function, so I am happy for pointers where to start for testing `PeerChangedResponse`.
=> Only read relevant nodes from database in PeerChangedResponse

CHANGELOG.md, hscontrol/mapper/tail_test.go, hscontrol/types/node.go, hscontrol/types/node_test.go, integration/auth_oidc_test.go, integration/dns_test.go, integration/dockertestutil/execute.go
This ensures that nodes which have a base domain set, will have a dot appended to their FQDN. This way, nodes in a netmap will look the same as they do when using tailscale.com services.
Fixes: https://github.com/juanfont/headscale/issues/2501
=> ensure final dot on node name

.github/workflows/test-integration-policyv2.yaml, .github/workflows/test-integration.yaml
From my lengthy comment for rational:
```
⋮ 130│          # Our integration tests are started like a thundering herd, often
⋮ 131│          # hitting limits of the various external repositories we depend on
⋮ 132│          # like docker hub. This will retry jobs every 5 min, 10 times,
⋮ 133│          # hopefully letting us avoid manual intervention and restarting jobs.
⋮ 134│          # One could of course argue that we should invest in trying to avoid
⋮ 135│          # this, but currently it seems like a larger investment to be cleverer
⋮ 136│          # about this.
⋮ 137│          # Some of the jobs might still require manual restart as they are really
⋮ 138│          # slow and this will cause them to eventually be killed by Github actions.
```
=> more wait, more retry

hscontrol/types/users.go, hscontrol/types/users_test.go
=> add casbin user test

CHANGELOG.md, hscontrol/types/config.go, hscontrol/types/config_test.go
=> config: disallow same server url and base_domain

CHANGELOG.md, hscontrol/oidc.go, hscontrol/types/users.go
This builds on #2493 to get more useful information from userinfo if it is not set in the claim.
@benley would be interested to have your review on this pr.
Fixes #2516
=> oidc: try to get username from userinfo

hscontrol/auth.go, hscontrol/grpcv1.go, hscontrol/oidc.go, integration/route_test.go
=> auth: ensure that routes are autoapproved when the node is stored

hscontrol/debug.go, hscontrol/mapper/mapper.go, hscontrol/policy/matcher/matcher.go, hscontrol/policy/pm.go, hscontrol/policy/policy.go, hscontrol/policy/policy_test.go, hscontrol/policy/v1/policy.go, hscontrol/policy/v1/policy_test.go, hscontrol/policy/v2/policy.go, hscontrol/policy/v2/policy_test.go, hscontrol/types/node.go, hscontrol/types/node_test.go
This PR makes the `Match`es that are computed from `FilterRule`s part of the `Policy` interface, so that they don't have to be recomputed at each call to `Node.CanAccess`. There have already been some discussion on this approach in #2416.
=> Make matchers part of the Policy interface

hscontrol/policy/v2/filter_test.go, hscontrol/policy/v2/policy.go, hscontrol/policy/v2/types.go, hscontrol/policy/v2/types_test.go
=> error on undefined host in policy

CHANGELOG.md, cmd/headscale/cli/policy.go
add a cli check command that tries to read in the policy and reports errors.
=> cmd: add policy check command

.goreleaser.yml
See https://goreleaser.com/deprecations/#archivesformat and https://goreleaser.com/deprecations/#nfpmsbuilds
=> Fix goreleaser deprecation warnings

docs/packaging/postinstall.sh
When creating the headscale user and group, create both as system groups rather than creating them as 'user' groups.
FIXES #2278
=> feat: Create headscale user and group as system user/groups

hscontrol/policy/route_approval_test.go, hscontrol/policy/v2/policy.go, hscontrol/policy/v2/types.go, hscontrol/policy/v2/types_test.go
=> policy/v2: separate exit node and 0.0.0.0/0 routes

CHANGELOG.md
These steps are easier to accomplish and require only Headscale 0.26. They also work when a user has already upgraded the database.
See: #2567
=> Simplify policy migration

cmd/headscale/cli/utils.go, hscontrol/app.go, hscontrol/db/db.go, hscontrol/db/node.go, hscontrol/poll.go, hscontrol/types/node.go, integration/auth_key_test.go
=> bring back last_seen in database

hscontrol/db/db.go, hscontrol/types/users.go, hscontrol/types/users_test.go
=> users: harden, test, and add cleaner of identifier

.goreleaser.yml
just so we can control when it goes out and not CI
=> goreleaser: always do draft

.github/workflows/test-integration.yaml, CHANGELOG.md, docs/about/features.md, hscontrol/policy/v2/types.go, hscontrol/policy/v2/types_test.go, integration/acl_test.go
This implements two autogroups `autogroup:member` and `autogroup:tagged`. I talked with @kradalby about leaving out `autogroup:self` for now, as that is a bit trickier in the end.
The logic of the autogroups and test is taken from the draft pr #2230, but it has been implemented for the new policy structure.
=> feat: add autogroup:member, autogroup:tagged

hscontrol/templates/register_web.go, integration/scenario.go
This change makes editing the generated command easier. For example, after pasting into a terminal, the cursor position will be near the username portion which requires editing.
=> web: change node registration parameter order

docs/ref/integration/web-ui.md
This PR adds [headscale-console](https://github.com/rickli-cloud/headscale-console) to the documentation. The table was reformatted to accommodate the additional text.
headscale-console is not a traditional UI that directly binds into the REST API. Instead, it was inspired by the [Tailscale WASM client](https://github.com/tailscale/tailscale/tree/main/cmd/tsconnect) and slowly grew supporting more and more protocols (SSH, VNC & RDP). It also includes an optional self-service tsnet server binding into the headscale GRPC unix socket.
=> Add headscale-console web UI to docs

.github/workflows/build.yml, .github/workflows/check-tests.yaml, .github/workflows/lint.yml, .github/workflows/release.yml, .github/workflows/test-integration.yaml, .github/workflows/test.yml
> Headscale is open to code contributions for bug fixes without discussion.
Hopefully this counts as a bug fix 😅 If not, I'm happy to close the PR and discuss the change :)
The `DeterminateSystems/magic-nix-cache-action` action has been [deprecated](https://determinate.systems/posts/magic-nix-cache-free-tier-eol/) and no longer works. This PR replaces it with the `nix-community/cache-nix-action` action, which is actively maintained. It also replaces the `DeterminateSystems/nix-installer-action` action with the `nixbuild/nix-quick-install-action` action, which is required for the cache action to work. The cache has been configured to restore based on the runner's OS and architecture, so it should work on any runner.
=> Replace magic-nix-cache-action

CHANGELOG.md, hscontrol/noise.go
`POST /machine/map` requests are processed by extracting the Node from the public `NodeKey` provided in the request, without any additional verification. This allows an attacker who possesses the public key of any Node in the network to:
1. Establish a Noise connection using a new machine key,
2. Submit a `MapRequest` containing a `NodeKey` that does not belong to them, and
3. Receive a stream of `MapResponse`s.
As a result, the attacker can learn sensitive details about the entire Tailnet.
The current approach implicitly trusts the `NodeKey` in the request, even though the client has not proven ownership of its corresponding private key.
Instead, we should retrieve the Node based on the machine key used in the Noise connection, as the client must possess the corresponding private key to …
=> Fix `/machine/map` endpoint vulnerability

hscontrol/util/dns.go
The docstring for `ValidateUsername()` states:
>   It must be at least 2 characters long, start with a letter, and
>   contain only letters, numbers, hyphens, dots, and underscores.
=> Ensure that a username starts with a letter

hscontrol/app.go
This patch updates the log message on SIGHUP to only mention reloading
of the ACL policy.
=> Clarify SIGHUP log message

hscontrol/handlers.go
Stumbled upon this typo when doing #2643 , and thought I might as well change it.
Discovered that the error is no longer used, after #2398 was merged.
=> Fixed typo in parseCapabilityVersion, and removed unused error

.github/workflows/integration-test-template.yml
Looks like we mostly not winning by retrying.
=> .github/workflows: reduce integration retry to 3

docs/setup/install/container.md, docs/usage/getting-started.md
Once approved, I'll also backport this to the 0.26.x docs
=> The preauthkeys commands expect a user id instead of a username

.github/workflows/lint.yml
The argument `--format=colored-line-number` is invalid and `--out-format=colored-line-number` is no longer available. Fixup according to the migration guide.
Tested this locally via:
```console
$ nix develop
$ golangci-lint run --new-from-rev=3123d5286bbeb1d4958cec3c92d5a0969b201a9b --output.text.path=stdout --output.text.print-linter-name --output.text.print-issued-lines --output.text.colors
hscontrol/oidc.go:281:29: printf: (*github.com/rs/zerolog.Event).Msgf format %s has arg userinfo of wrong type *github.com/coreos/go-oidc/v3/oidc.UserInfo (govet)
log.Info().Msgf("UserInfo: %s", userinfo)
^
hscontrol/oidc.go:404:33: printf: (*github.com/rs/zerolog.Event).Msgf format %s has arg oauth2Token of wrong type *golang.org/x/oauth2.Token (govet)
log.Info().Msgf("oauth2 Token: %s", …
```
=> Fix invocation of golangci-lint

CHANGELOG.md, hscontrol/oidc.go, hscontrol/types/users.go
This patch includes some changes to the OIDC integration in particular:
- Make sure that userinfo claims are queried *before* comparing the user with the configured allowed groups, email and email domain.
- Update user with group claim from the userinfo endpoint which is required for allowed groups to work correctly. This is essentially a continuation of #2545.
- Let userinfo claims take precedence over id token claims.
With these changes I have verified that Headscale works as expected together with Authelia without the documented escape hatch [0], i.e. everything works even if the id token only contain the iss and sub claims.
[0]: https://www.authelia.com/integration/openid-connect/headscale/#configuration-escape-hatch
=> OIDC: Query userinfo endpoint before verifying user

docs/ref/dns.md
Just a small documentation fix.
Tailscale has moved Extra DNS mapping to a different location in its codebase.
https://github.com/tailscale/tailscale/blob/v1.86.5/ipn/ipnlocal/node_backend.go#L662
_I suggest to use the link to the latest version v1.86.5, since the difference between v1.86.5 and v1.84.3 (the current headscale used) is only in line numbers._
=> Minor documentation correction
